/**
 * COPY_EN — 英文文案 (peak-mall demo)
 *
 * 只翻译英文版需要的 keys;其他 keys 通过 useT() 缺失时自动 fallback 到中文 COPY。
 * 3 个目标页面用到的 keys 必须全部在这里(供首屏 SSR + 客户端切换使用)。
 *
 * 设计原则:
 * - 扁平结构与 COPY 对齐,缺啥补啥
 * - 不留机翻痕迹,适合英文母语者阅读
 * - 货币/符号不在 copy 中,渲染层按 locale 切换
 */

export const COPY_EN = {
  brand: {
    name: 'Peak Mall',
    slogan: 'PEAK MALL',
    shortName: 'Peak',
    intro: 'Curated global finds · Authentic guaranteed. Ships to 28 countries · 7-day no-reason returns.',
  },

  nav: {
    home: 'Home',
    all: 'All',
    new: 'New',
    hot: 'Hot',
    orders: 'My orders',
    after: 'After-sales',
    about: 'About',
  },

  currencyLabel: {
    USD: 'USD US Dollar',
    CNY: 'CNY Yuan',
    EUR: 'EUR Euro',
    GBP: 'GBP Pound',
    JPY: 'JPY Yen',
    KRW: 'KRW Won',
    AUD: 'AUD A Dollar',
    CAD: 'CAD C Dollar',
  },

  /** G3: fx converter + history */
  fx: {
    title: 'FX rates',
    subtitle: 'Live converter + 7-day trend',
    convertTitle: 'Convert',
    amount: 'Amount',
    from: 'From',
    to: 'To',
    result: 'Result',
    rate: 'Current rate',
    historyTitle: '7-day trend',
    historyRange: 'Range',
    range7d: '7 days',
    range30d: '30 days',
    ratesTitle: 'Major rates',
    noChange: 'Flat',
    upLabel: 'up',
    downLabel: 'down',
    lastUpdate: 'Updated',
  },

  langLabel: { zh: 'Chinese', en: 'EN' },

  header: {
    welcome: 'Welcome to Peak Mall',
    login: 'Sign in / Register',
    searchAria: 'Site search',
    inputAria: 'Search products',
    submit: 'Go',
    orderStatus: 'Order status',
    logout: 'Sign out',
    logoutAria: 'Sign out',
    /** S1: search suggestions dropdown */
    sugHistory: 'Recent',
    sugHot: 'Popular categories',
    sugEmpty: 'No suggestions',
    sugClear: 'Clear',
    sugNoHistory: 'No search history yet',
    clear: 'Clear',
    /** S2: mobile search bar */
    mobileSearchOpen: 'Open search',
    mobileSearchClose: 'Close search',
    /** S4: global shortcut hint */
    shortcutHint: '⌘K',
    shortcutHintLabel: 'Press ⌘K to search',
    /** S5: spelling correction */
    didYouMean: 'Did you mean',
    didYouMeanSuffix: '?',
  },

  announcement: {
    defaultTag: 'Notice',
    defaultText: 'Free shipping over $50 · 7-day no-reason returns',
  },

  card: {
    wishlistOn: '♥',
    wishlistOff: '♡',
    addedToCart: '✓ Added',
  },

  modal: {
    close: 'Close',
    closeSymbol: '✕',
    coverEmoji: '📦',
  },

  cta: {
    addToCart: 'Add to cart',
    buyNow: 'Buy now',
    viewDetail: 'View detail',
    backToHome: 'Back to home',
    goLogin: 'Sign in',
    goRegister: 'Create account',
    subscribe: 'Subscribe',
    emailPh: 'Enter your email',
    label: 'Limited offer',
    title: 'Subscribe for member deals',
    sub: 'New users save more on first order · Weekly picks · Unsubscribe anytime',
    success: 'Subscribed! Check your inbox for the welcome email.',
    error: 'Please enter a valid email address.',
    disclaimer: 'We respect your privacy. Unsubscribe anytime. See Privacy Policy.',
  },

  hero: {
    h1: 'Curated global goods',
    h2: 'Quality living, one stop',
    sub: 'Tech · Smart home · Ships to 28 countries · 7-day no-reason returns',
    eyebrow: 'Limited time · Free shipping over $50',
    ctaPrimary: 'Shop now',
    ctaSecondary: 'See bestsellers',
    socialProof: '100,000+ happy shoppers',
    rating: '4.9 / 5.0',
    floatingCard1: 'Shipped',
    floatingCard1Sub: 'Arrives in 3 days',
    floatingCard2: 'Great experience, fast support, on-time logistics.',
    searchPlaceholder: 'Search 160k items · laptops / earbuds / vacuums …',
    searchHint: 'Popular:',
    searchTags: ['Business laptops', 'Wireless earbuds', 'Robot vacuums', 'Smart watches'],
    trust: {
      countries: 'Countries served',
      countryUnit: '+',
      support: 'Support',
      supportUnit: '',
      return: 'No-reason returns',
      returnUnit: ' days',
      authentic: 'Authentic',
      authenticUnit: '',
    },
  },

  home: {
    browseByCat: 'Browse by category',
    exploreCategories: 'Explore curated categories',
    cat1Desc: 'From business laptops to smart wearables, covering every facet of digital life',
    cat2Desc: 'Smart home upgrades that make everyday life easier',
    catOfItems: (n: number) => `${n} items`,
    cat1: 'Electronics',
    cat2: 'Home appliances',
  },

  flashSale: {
    label: 'Flash sale',
    title: '12-hour limited deal',
    scope: 'Site-wide · Once only',
    endsIn: 'Ends in',
    stock: 'Stock left',
    save: 'Save',
  },

  service: {
    shipping: { title: 'Multi-warehouse shipping', desc: 'Ships to 28 countries' },
    return: { title: 'Hassle-free returns', desc: '7-day no-reason' },
    support: { title: 'Concierge support', desc: 'Online 13:00-23:30' },
    authentic: { title: 'Authentic guaranteed', desc: '10x compensation if fake' },
  },

  topSelling: {
    label: 'Bestsellers this week',
    title: 'TOP 5 user favorites',
    viewAll: 'See full ranking',
    sold: 'sold',
  },

  rec: {
    label: 'Picked for you',
    title: 'Curated picks',
    sub: 'Smart picks based on your browsing and trending data',
    sortBy: 'Sort',
    sortDefault: 'Featured',
    sortPriceAsc: 'Price: low to high',
    sortPriceDesc: 'Price: high to low',
    sortRating: 'Top rated',
    empty: 'No items in this category, try another',
  },

  quality: {
    label: 'Quality zone',
    title: 'Two curated collections',
    collection: 'Collection',
    cat1: 'Tech',
    cat2: 'Home',
    b1Title: 'Tech flagship zone',
    b1Sub: 'From business to daily entertainment — flagship quality, global selection',
    b1Bullets: ['Business laptops · flagship performance', 'Smart wearables · health tracking', 'Audio · immersive experience'],
    b1Cta: 'Shop tech',
    b2Title: 'Smart home zone',
    b2Sub: 'Tech that lights up everyday life and makes housework lighter',
    b2Bullets: ['Robot vacuums · LiDAR navigation', 'Smart speakers · voice control', 'Security cameras · 24h watch'],
    b2Cta: 'Shop home',
  },

  newArrivals: {
    label: 'New arrivals',
    title: 'Just landed · Be first',
    viewAll: 'See all new arrivals',
    badge: 'NEW',
    hot: 'Hot',
  },

  testimonial: {
    label: 'Real reviews',
    title: 'Hear what they say',
    aggregate: '4.9 · from 10,000+ users',
    q1: 'My first order from Peak Mall exceeded expectations. Sturdy packaging, fast shipping, quality that justifies the price.',
    n1: 'Ms. Chen',
    r1: 'Beijing · Tech enthusiast',
    q2: 'Bought a business laptop and wireless earbuds, both authentic and cheaper than retail. Support was also professional.',
    n2: 'Mr. Li',
    r2: 'Shanghai · Business user',
    q3: 'The smart home gear is solid — the vacuum is smart and the app control is smooth. Already my third order.',
    n3: 'Ms. Wang',
    r3: 'Shenzhen · Designer',
  },

  promise: {
    label: 'Our promise',
    title: 'Four guarantees, shop with confidence',
  },

  cart: {
    title: 'My cart',
    empty: 'Your cart is empty',
    emptyDesc: 'Go find something nice',
    total: 'Total',
    checkout: 'Checkout',
    clear: 'Clear cart',
    continue: 'Continue shopping',
    qty: 'Qty',
    subtotal: 'Subtotal',
    orderPlaced: 'Order placed',
    orderPlacedDesc: 'Check status in My Orders',
    removed: 'Removed',
    freeShippingNote: 'Free shipping',
    shippingFee: '$5.00',
    shippingLabel: 'Shipping',
    qtyDecLabel: 'Decrease quantity',
    qtyIncLabel: 'Increase quantity',
    /** A1: per-item selection */
    selectAll: 'Select all',
    selectedCount: (n: number, total: number) => `${n} of ${total} selected`,
    selectedEmpty: 'Pick at least one item to check out',
    /** A2: coupon */
    couponTitle: 'Promo code',
    couponPlaceholder: 'Enter promo code',
    couponApply: 'Apply',
    couponRemove: 'Remove',
    couponApplied: (code: string) => `${code} applied`,
    couponInvalid: 'Invalid or expired code',
    couponInvalidMin: 'Requires $200 minimum',
    /** Discount breakdown line */
    discountLabel: 'Discount',
    /** Available hints */
    couponHints: 'Try SAVE10 (10% off) / FREESHIP (free shipping) / VIP20 ($20 off $200+)',
    /** G1: last coupon reuse */
    lastCoupon: (code: string) => `Last used ${code}`,
    lastCouponReuse: 'Apply again',
  },

  search: {
    title: 'Search results',
    subCount: (n: number, q: string) => `${n} items match “${q}”`,
    subEmpty: (q: string) => `No items match “${q}”`,
    suggest: 'Try other keywords, or head back home to keep browsing',
    clear: 'Clear',
    backHome: 'Back to home',
    hot: 'Popular searches',
    hotTags: ['Laptops', 'Earbuds', 'Robot vacuums', 'Smart watches', 'Humidifiers'],
  },

  orders: {
    title: 'My orders',
    empty: 'No orders yet',
    emptyDesc: 'Place an order from cart to see it here',
    startShopping: 'Browse products',
    itemCount: (n: number) => `${n} items`,
    orderId: 'Order ID',
    placedAt: 'Placed',
    amount: 'Total',
    viewDetail: 'View detail',
    status: {
      pending: 'Pending',
    },
    statusPending: 'Pending',
    statusPaid: 'Paid',
    statusShipped: 'Shipped',
    statusDelivered: 'Delivered',
    /** A3: tab + search */
    tabAll: 'All',
    tabPending: 'Pending',
    tabPaid: 'Paid',
    tabShipped: 'Shipped',
    tabDelivered: 'Delivered',
    tabCancelled: 'Cancelled',
    searchPlaceholder: 'Search by ID or item name',
    searchAria: 'Search orders',
    noMatch: 'No matching orders',
    noMatchDesc: 'Try a different keyword or status tab',
    /** A4: cancel / buy again */
    cancel: 'Cancel order',
    cancelConfirm: 'Cancel this order?',
    cancelHint: 'This will mark the order as cancelled. This cannot be undone.',
    cancelled: 'Cancelled',
    buyAgain: 'Buy again',
    buyAgainOk: 'Added to cart — redirecting…',
    cancelledTag: 'Cancelled',
    /** A5: order detail expand */
    hideDetail: 'Hide details',
    payment: 'Payment',
    paymentNone: 'Not paid',
    paymentBrand: (b: string) => `${b}`,
    paymentLast4: (n: string) => `•••• ${n}`,
    paymentAuth: (a: string) => `Auth ${a}`,
    cancelledAt: 'Cancelled at',
    timeline: 'Timeline',
    timelinePlaced: 'Placed',
    timelinePaid: 'Paid',
    timelineShipped: 'Shipped',
    timelineDelivered: 'Delivered',
    timelineCancelled: 'Cancelled',
  },

  wishlist: {
    title: 'My wishlist',
    empty: 'No saved items yet',
    emptyDesc: 'Tap the heart button to add items you love',
    addToCart: 'Add to cart',
    removeAll: 'Clear wishlist',
    addedAt: 'Saved',
  },
  userSidebar: {
    groupMall: 'Mall',
    groupDistribute: 'Distribution',
    groupAccount: 'Account',
    groupMine: 'Mine',
    navShopHome: 'Shop home',
    navShopAll: 'All products',
    navShopNew: 'New arrivals',
    navShopHot: 'Hot deals',
    navCart: 'Cart',
    navMyOrders: 'My orders',
    navMyAccount: 'My account',
    navCommissions: 'Commissions',
    navWithdraw: 'Withdraw',
    navWithdrawAddr: 'Withdraw address',
    navPersonalCenter: 'Profile',
    navChangePassword: 'Change password',
    navFundPassword: 'Fund password',
    navMyAddress: 'My addresses',
    navMyWishlist: 'My wishlist',
    navMyAftersale: 'My aftersale',
    logout: 'Sign out',
  },
  address: {
    title: 'Addresses',
    empty: 'No saved addresses',
    emptyDesc: 'Add a shipping address for faster checkout',
    addNew: 'Add address',
    edit: 'Edit',
    remove: 'Remove',
    setDefault: 'Set default',
    default: 'Default',
    name: 'Recipient',
    phone: 'Phone',
    region: 'Region',
    detail: 'Street address',
    save: 'Save',
    cancel: 'Cancel',
    removeConfirm: 'Remove this address?',
    removeHint: 'This address will be removed from your address book. This cannot be undone.',
    removed: 'Address removed',
    /** D3: phone validation */
    phonePh: '11 digits, e.g. 13800001234',
    /** D4: tag selector + form errors */
    tag: 'Tag',
    tagHome: 'Home',
    tagOffice: 'Office',
    tagOther: 'Other',
    nameRequired: 'Recipient name is required',
    savedFlash: 'Address saved',
    phoneInvalid: 'Enter a valid 11-digit phone number (starts with 1[3-9])',
  },
  checkout: {
    title: 'Confirm order',
    subtitle: 'Pick a shipping address and payment method',
    sectionAddress: 'Shipping address',
    noAddress: 'No shipping address',
    noAddressDesc: 'Add one first to continue',
    goAddresses: 'Add address',
    sectionPayment: 'Payment method',
    methodCard: 'Credit / debit card',
    methodCardDesc: 'Recommended — 3-D Secure verified',
    methodVisa: 'Visa',
    methodVisaDesc: 'Recommended — 3-D Secure verified',
    methodMastercard: 'Mastercard',
    methodMastercardDesc: 'Recommended — 3-D Secure verified',
    sectionSummary: 'Order summary',
    itemCount: (n: number) => `${n} item${n === 1 ? '' : 's'}`,
    subtotal: 'Subtotal',
    shipping: 'Shipping',
    freeShipping: 'Free',
    total: 'Total',
    placeOrder: 'Place order',
    placeOrderNeedAddress: 'Please add or select a shipping address',
    orderSuccess: 'Order placed',
    orderSuccessDesc: 'Check status in My orders',
    selectDefault: 'Use default address',
    /** Cashier */
    cashier: 'Checkout',
    cashierSubtitle: 'Pick a payment method',
    payBy: 'Pick a payment method',
    cardNumber: 'Card number',
    cardNumberPh: '4242 4242 4242 4242',
    cardExp: 'Expires (MM/YY)',
    cardExpPh: '08/29',
    cardCvv: 'CVV',
    cardCvvPh: '123',
    cardHolder: 'Cardholder name',
    cardHolderPh: 'As shown on card',
    cardEncrypted: 'Encrypted in transit. We only store the last 4 digits and brand for reference.',
    brandDetected: (b: string) => `Detected ${b}`,
    brandUnknown: 'Enter a valid card number',
    confirmPay: 'Confirm payment',
    payFailed: 'Payment failed — try again or pick another method',
    payProcessing: 'Processing payment…',
  },
  aftersale: {
    title: 'After-sales',
    empty: 'No after-sales requests',
    emptyDesc: 'Submit a request here when you need help with an order',
    requestBtn: 'Request after-sales',
    orderId: 'Order',
    reason: 'Reason',
    statusPending: 'Pending',
    statusApproved: 'Approved',
    statusRejected: 'Rejected',
    statusCompleted: 'Completed',
    statusRefunded: 'Refunded',
    note: 'Notes',
    submitOk: 'Request submitted',
    viewOrder: 'View order',
    /** G2: detail modal */
    detailTitle: 'After-sales details',
    timelineTitle: 'Progress',
    stepSubmitted: 'Request submitted',
    stepReviewing: 'Under review',
    stepApproved: 'Approved',
    stepDone: 'Resolved',
    closeBtn: 'Close',
    createdAt: 'Created at',
    expectTime: 'Reply within 24 hours',
    refundAmount: 'Refund amount',
    refundMethod: 'Refund method',
    refundToOrigin: 'Original payment method',
    contactCs: 'Contact support',
  },
  about: {
    title: 'About Peak Mall',
    subtitle: 'Global curation · Genuine guarantee',
    heroEyebrow: 'Our story',
    heroLead: 'From one peak to a million homes',
    heroBody: 'Founded in 2021 and headquartered in Shenzhen, Peak Mall was built on a simple belief: great products should not be limited by geography. We work with 28 countries on warehousing and certification so the brands we love can reach Chinese households with confidence.',
    missionTitle: 'Our mission',
    missionBody: 'Help every Chinese household buy global, authentic goods at transparent prices — with after-sales they can actually rely on.',
    statsTitle: 'By the numbers',
    statCountries: '28',
    statCountriesLabel: 'Countries served',
    statShops: '2,000+',
    statShopsLabel: 'Brand partners',
    statUsers: '100,000+',
    statUsersLabel: 'Happy shoppers',
    statOrders: '500,000+',
    statOrdersLabel: 'Orders fulfilled',
    promiseTitle: 'Four guarantees',
    promiseShipTitle: 'Multi-warehouse',
    promiseShipDesc: 'Distributed warehouses — ships within 48 hours',
    promiseReturnTitle: 'Easy returns',
    promiseReturnDesc: '7-day no-questions returns, end-to-end tracking',
    promiseServiceTitle: 'Real service',
    promiseServiceDesc: '1-on-1 support for pre-sales and after-sales',
    promiseGenuineTitle: '100% genuine',
    promiseGenuineDesc: 'Sourced direct — 10x refund on counterfeits',
    teamTitle: 'The team',
    teamLead: 'A small group, one mission',
    teamBody: '50+ people across Shenzhen, Tokyo and Singapore — operations, design, warehousing, support and engineering. Each of us is here for one reason: getting the thing you picked out to your door, intact.',
    ctaTitle: 'Still have questions?',
    ctaBody: 'Support is online 13:00–23:30 (UTC+8). Tap the Telegram bubble in the bottom-right corner.',
    ctaButton: 'Contact support',
  },
  orderDetail: {
    title: 'Order details',
    notFound: 'Order not found',
    notFoundDesc: 'This order may have been removed or the link is wrong.',
    sectionItems: 'Items',
    sectionShipping: 'Shipping address',
    sectionPayment: 'Payment',
    sectionStatus: 'Order status',
    statusPending: 'Pending payment',
    statusPaid: 'Paid',
    statusShipped: 'Shipped',
    statusDelivered: 'Delivered',
    statusRefunded: 'Refunded',
    statusCancelled: 'Cancelled',
    subtotal: 'Subtotal',
    shipping: 'Shipping',
    total: 'Total',
    itemCount: (n: number) => `${n} item${n === 1 ? '' : 's'}`,
    copyOrderId: 'Copy order ID',
    copied: 'Copied',
    payNow: 'Pay now',
    contactCs: 'Contact support',
  },
  funds: {
    title: 'My funds',
    subtitle: 'Balance, frozen amount and transaction history',
    available: 'Available',
    frozen: 'Frozen',
    earnedTotal: 'Total earned',
    withdrawnTotal: 'Total withdrawn',
    recentFlows: 'Recent activity',
    flowEmpty: 'No transactions yet',
    flowTypeIn: 'Credit',
    flowTypeOut: 'Debit',
    flowTypeFrozen: 'Frozen',
    flowTypeUnfreeze: 'Released',
    topupNow: 'Top up',
    withdrawNow: 'Withdraw',
    /** B5: filter + export */
    monthLabel: 'Month',
    monthAll: 'All months',
    typeLabel: 'Type',
    typeAll: 'All types',
    export: 'Export CSV',
    exported: (n: number) => `Exported ${n} transactions`,
    noMatch: 'No matching transactions',
  },
  team: {
    title: 'My team',
    subtitle: 'Downline members and the commission they generate',
    memberCount: (n: number) => `${n} members`,
    level1: 'Level 1',
    level2: 'Level 2',
    level3: 'Level 3',
    totalCommission: 'Team commission total',
    thisMonthCommission: 'This month',
    inviteTitle: 'My invite code',
    inviteDesc: 'Share your code — anyone who signs up with it becomes your downline automatically.',
    inviteCopy: 'Copy',
    inviteCopied: 'Copied',
    inviteCopiedToast: (code: string) => `Copied ${code}`,
    empty: 'No downline yet',
    emptyDesc: 'Share your code to recruit your first promoter.',
    sectionMembers: 'Members',
    memberJoinDate: 'Joined',
    memberOrderCount: 'Orders',
    memberCommission: 'Commission',
    /** F1: member detail modal */
    memberDetailTitle: 'Member detail',
    memberClose: 'Close',
    memberAvgOrder: 'Avg order value',
    memberRecent: 'Recent commissions',
    memberRecentEmpty: 'No commissions yet',
    memberCopyInviteLink: 'Copy invite link',
    memberLinkCopied: 'Invite link copied',
  },
  commissions: {
    title: 'Commissions',
    empty: 'No commissions yet',
    emptyDesc: 'Referral order settlements show up here',
    totalEarned: 'Total earned',
    thisMonth: 'This month',
    pending: 'Pending',
    available: 'Available',
    source: 'Source',
    order: 'Order',
    amount: 'Amount',
    rate: 'Rate',
    date: 'Date',
    statusSettled: 'Settled',
    statusPending: 'Pending',
    /** B3: filter + export */
    tabAll: 'All',
    tabSettled: 'Settled',
    tabPendingTab: 'Pending',
    sourceDirect: 'Direct',
    sourceLevel1: 'Level 1',
    sourceLevel2: 'Level 2',
    monthLabel: 'Month',
    monthAll: 'All months',
    export: 'Export CSV',
    exported: (n: number) => `Exported ${n} records`,
    noMatch: 'No matching records',
    noMatchDesc: 'Try adjusting the status or month filter',
    /** B7: commission detail modal */
    detailTitle: 'Commission detail',
    detailClose: 'Close',
    orderId: 'Order ID',
    product: 'Product',
    orderAmount: 'Order amount',
    commissionRate: 'Commission rate',
    commissionAmount: 'Commission amount',
    settledAt: 'Settled at',
    sourceInfo: 'Source info',
    referredBy: 'Referred by',
    tier: 'Tier',
    viewOrder: 'View order',
    /** B8: per-row export */
    exportRow: 'Export this',
    rowExported: 'Single row exported',
  },
  withdraw: {
    title: 'Withdraw',
    available: 'Available',
    pending: 'Pending',
    withdrawn: 'Withdrawn',
    apply: 'Request withdraw',
    amount: 'Amount',
    address: 'Payout address',
    selectAddress: 'Choose payout address',
    noAddress: 'No payout address yet — add one in Payout address first',
    history: 'Withdraw history',
    empty: 'No withdraw records',
    /** C3: filter + export */
    tabAll: 'All',
    searchPlaceholder: 'Search id / address',
    searchAria: 'Search withdrawals',
    noMatch: 'No matching records',
    noMatchDesc: 'Try adjusting the status or search',
    export: 'Export CSV',
    exported: (n: number) => `Exported ${n} records`,
    amountCol: 'Amount',
    addressCol: 'Payout address',
    date: 'Date',
    statusPending: 'Processing',
    statusApproved: 'Approved',
    statusRejected: 'Rejected',
    statusCompleted: 'Completed',
    submitted: 'Withdraw request submitted',
    minAmount: 'Minimum withdraw is $10',
    /** C1: fund password modal */
    fundPwdPrompt: 'Enter your fund password',
    fundPwdHint: '6 digits, used for withdrawals',
    fundPwdWrong: 'Wrong fund password — try again',
    fundPwdForgot: 'Forgot it?',
    cancel: 'Cancel',
    confirm: 'Confirm withdraw',
    /** C2: fee preview */
    fee: 'Fee',
    feeRate: '(2% rate)',
    actualReceive: 'You receive',
    feeHint: 'Minimum $10. You receive = amount − fee',
    insufficientBalance: 'Insufficient available balance',
    /** C4: withdraw detail modal */
    detailTitle: 'Withdraw detail',
    detailClose: 'Close',
    net: 'You receive',
    networkFee: 'Network fee',
    appliedAt: 'Applied at',
    approvedAt: 'Approved at',
    completedAt: 'Completed at',
    rejectedAt: 'Rejected at',
    rejectReason: 'Reject reason',
    timeline: 'Timeline',
    timelineApplied: 'Applied',
    timelineApproved: 'Approved',
    timelineCompleted: 'Completed',
    timelineRejected: 'Rejected',
    copyAddress: 'Copy address',
    addressCopied: 'Address copied',
  },
  withdrawAddress: {
    title: 'Payout addresses',
    empty: 'No payout addresses',
    emptyDesc: 'Add a crypto or bank account to receive payouts',
    addNew: 'Add payout address',
    type: 'Type',
    typeCrypto: 'Crypto',
    typeBank: 'Bank',
    label: 'Label',
    address: 'Address / account',
    network: 'Network',
    save: 'Save',
    cancel: 'Cancel',
    removeConfirm: 'Remove this payout address?',
    remove: 'Remove',
    setDefault: 'Set default',
    default: 'Default',
    copy: 'Copy',
    copied: 'Copied',
    copyErr: 'Copy failed',
    addrRequired: 'Address or account number is required',
    labelRequired: 'Label is required',
    networkRequired: 'Crypto addresses must pick a network',
    bankName: 'Bank name',
    bankNamePh: 'e.g. Chase / Bank of China',
    bankHolder: 'Account holder',
    bankHolderPh: 'Full name on the account',
    bankSwift: 'SWIFT / routing',
    bankSwiftPh: 'SWIFT code or ABA routing number',
    bankAddr: 'Bank address',
    bankAddrPh: 'Optional',
    networks: {
      TRC20: 'TRC20 (Tron)',
      ERC20: 'ERC20 (Ethereum)',
      BEP20: 'BEP20 (BSC)',
      SOL: 'SOL (Solana)',
      POLYGON: 'Polygon',
      ARBITRUM: 'Arbitrum',
    },
  },
  security: {
    changePassword: 'Change password',
    changeFundPassword: 'Fund password',
    currentPassword: 'Current password',
    newPassword: 'New password',
    confirmPassword: 'Confirm new password',
    save: 'Save',
    cancel: 'Cancel',
    pwdMismatch: 'Passwords do not match',
    pwdTooShort: 'Password must be at least 6 characters',
    savedOk: 'Saved',
    fundPwdHint: 'Fund password is used for withdrawals — 6 digits',
    pwdIntro: 'At least 6 characters. Changes take effect immediately.',
    fundPwdIntro: 'Fund password is exactly 6 digits, used to authorise withdrawals.',
  },

  profile: {
    title: 'Account',
    welcome: 'Welcome back',
    notLoggedIn: 'Not signed in',
    nickname: 'Nickname',
    email: 'Email',
    edit: 'Edit',
    myOrders: 'My orders',
    myWishlist: 'My wishlist',
    cart: 'Cart',
    settings: 'Settings',
    logout: 'Sign out',
    memberSince: 'Member since',
    goLogin: 'Sign in',
  },

  auth: {
    loginTitle: 'Sign in to Peak Mall',
    loginSub: 'Use any email & password (demo mode)',
    registerTitle: 'Create your account',
    registerSub: 'Join 100k+ happy shoppers',
    emailLabel: 'Email',
    welcomeBack: (name: string) => `Welcome, ${name}`,
    announce: 'Sign in for member pricing · Track order history anytime',
    loginErrorShort: 'Password must be at least 6 characters',
    registerErrorShort: 'Password must be at least 6 characters',
    loginErrorGeneric: 'Sign in failed',
    registerErrorGeneric: 'Registration failed',
    loggedInAs: (email: string, at: string) => `Signed in as ${email} · since ${at}`,
    demoBannerTitle: 'Demo account',
    demoBannerBody: 'Demo project: any valid email + a password of at least 6 characters works. Use the example shown below to follow the source site flow.',
    demoCredsHint: 'Example: 01@demo.com / 123456',
    hero: 'Welcome to Peak Mall',
    login: 'Sign in',
    register: 'Create account',
    email: 'Email',
    emailPh: 'you@example.com',
    password: 'Password',
    passwordPh: 'At least 8 characters',
    password2: 'Confirm password',
    password2Ph: 'Re-enter your password',
    nickname: 'Nickname',
    nicknamePh: 'Pick a name you’ll remember',
    invite: 'Invite code',
    invitePh: 'Optional',
    remember: 'Remember me',
    pwMismatch: 'Passwords don’t match',
    errGeneric: 'Something went wrong, please try again',
  },

  label: {
    price: 'Price',
    category: 'Category',
    stock: 'Stock',
    pcs: 'pcs',
    inStock: 'In stock',
    outOfStock: 'Out of stock',
    createdAt: 'Listed',
    noDescription: 'No description provided.',
  },

  product: {
    spec: 'Specs',
    rating: 'Rating',
    related: 'You may also like',
    qty: 'Quantity',
    addSuccess: 'Added to cart',
    loginRequired: 'Please sign in first',
    featuresLabel: 'Features',
    specsLabel: 'Specifications',
    reviewsLabel: 'Reviews',
    shippingLabel: 'Shipping & returns',
    inStockShort: 'In stock',
    soldLabel: 'Sold',
    skuLabel: 'SKU',
    categoryLabel: 'Category',
    addedOnLabel: 'Listed',
    freeShipNote: 'Free worldwide shipping over $50 · 7-day no-reason returns',
    reviewsSummary: (n: number) => `Based on ${n} verified buyer reviews`,
    /** v29: detail enrichment */
    highlightsLabel: 'Highlights',
    specsGroupBase: 'Essentials',
    specsGroupPerf: 'Performance',
    specsGroupDisplay: 'Display & audio',
    specsGroupBattery: 'Battery & thermals',
    specsGroupPorts: 'Connectivity',
    specsGroupPackage: 'In the box & warranty',
    faqLabel: 'Frequently asked questions',
    reviewSortLabel: 'Sort by',
    reviewSortLatest: 'Most recent',
    reviewSortHelpful: 'Most helpful',
    reviewSortRatingDesc: 'Rating: high to low',
    reviewHelpfulBtn: 'Helpful',
    reviewHelpfulCount: (n: number) => `${n} found this helpful`,
    reviewFilterAll: 'All',
    reviewFilterWithPic: 'With photo',
    reviewFilterFiveStar: '5 stars',
    reviewFilterFourStar: '4 stars',
    reviewFilterVerified: 'Verified',
    reviewEmptyTitle: 'No reviews for this filter',
    reviewEmptyDesc: 'Try a different filter or browse all reviews.',
    faqShipping: 'How long does shipping take?',
    faqShippingA: 'Shipped from local warehouses within 48 business hours. Estimated 3–7 day delivery to 28 countries.',
    faqReturn: 'Do you offer 7-day no-reason returns?',
    faqReturnA: 'Yes. If anything feels off within 7 days, we cover return shipping and refund your original payment method.',
    faqWarranty: 'How long is the warranty?',
    faqWarrantyA: '1 year on the main unit, 6 months on the battery. Walk into any authorized service center with your order number.',
    faqInvoice: 'Can I get an invoice?',
    faqInvoiceA: 'Yes — leave your company name and tax id at checkout, then request an e-invoice from your order page within 15 business days.',
    faqOverseas: 'Will it work overseas? Keyboard layout?',
    faqOverseasA: 'Yes. EN / ZH / JA / KO input methods are supported. Layout ships US-default; bilingual stickers are included.',
    faqBulk: 'Do you offer bulk / corporate pricing?',
    faqBulkA: 'Yes. Orders of 10+ can request a quote; 30+ supports VAT invoices and custom configurations.',
    /** v30: right-side info column depth */
    flashSaleTitle: 'Flash sale',
    flashSaleEndsIn: 'Ends in',
    soldProgress: (sold: number, stock: number) => `${sold} sold · only ${stock} left in stock`,
    stockLowHint: 'Low stock',
    stockLowUnit: ' left',
    colorLabel: 'Color',
    colorGray: 'Space gray',
    colorSilver: 'Lunar silver',
    sizeLabel: 'Storage',
    size512: '512GB',
    size1tb: '1TB · + $99',
    guaranteeTitle: 'Service & guarantee',
    guarantee7day: '7-day returns',
    guarantee7dayDesc: 'Return within 7 days for any reason. We cover return shipping and refund your original payment.',
    guaranteeAuth: 'Authenticity',
    guaranteeAuthDesc: 'Shipped from authorized channels with original invoice and verification.',
    guaranteeShip: 'Global warehouse',
    guaranteeShipDesc: '28-country local warehouses. Ships within 48 hours, 3–7 day delivery.',
    guaranteeWarranty: '1-year warranty',
    guaranteeWarrantyDesc: '1 year on the main unit, 6 months on the battery. On-site service in 28 cities.',
    expandMore: 'Details',
    expandLess: 'Collapse',
    selectVariantHint: 'Please select a variant',
    saleBadge: 'Flash deal',
    /** v30: showcase images + video + comparison */
    productVideoLabel: 'Product video',
    playVideo: 'Play',
    productShowcaseLabel: 'Product gallery',
    compareLabel: 'Side-by-side comparison',
    compareThisRow: 'This model',
    compareOther: 'Others',
    /** v31: interactive depth — Q&A + nested replies + photo wall */
    qaTitle: 'Questions & answers',
    qaSubtitle: 'Ask before you buy · answered by buyers and our team',
    qaAllFilter: 'All',
    qaUnansweredFilter: 'Unanswered',
    qaAskBtn: 'Ask a question',
    qaAskTitle: 'Post a question',
    qaPlaceholder: 'Ask anything — compatibility, sizing, usage scenarios…',
    qaSubmitBtn: 'Post',
    qaCancelBtn: 'Cancel',
    qaCharLimit: (n: number) => `${n}/200 chars`,
    qaEmptyTitle: 'No questions yet',
    qaEmptyDesc: 'Try a different filter or ask your own',
    qaSellerBadge: 'Official',
    qaHelpfulBtn: 'Helpful',
    qaHelpfulCount: (n: number) => `${n} found this helpful`,
    qaAnswerBtn: 'Write answer',
    qaAnswerPlaceholder: 'Share your experience, up to 300 chars',
    qaAnswerSubmit: 'Submit answer',
    qaAskNameLabel: 'Name',
    qaAskNamePlaceholder: 'Nickname or anonymous',
    replyTitle: 'Seller reply',
    replyPlaceholder: 'Write the official response — buyers will see it',
    replySubmit: 'Submit reply',
    replyHelpfulBtn: 'Helpful',
    photoWallLabel: 'Customer photos',
    photoWallCount: (n: number) => `${n} customer photos`,
    photoWallEmpty: 'No customer photos yet',
    photoWallFilter: 'All',
  },

  cookie: {
    title: 'We use cookies',
    desc: 'For a better browsing experience, we use cookies to remember your preferences (cart, wishlist, language). Continuing means you agree.',
    accept: 'Got it',
    settings: 'Learn more',
    aria: 'Cookie consent',
    closeAria: 'close',
    emoji: '🍪',
  },

  notFound: {
    eyebrow: '404',
    title: 'Got lost?',
    desc: "The page you're looking for doesn't exist — it may have been removed or the link is mistyped. Head home or check the bestsellers.",
    home: 'Back to home',
    hot: 'See bestsellers',
    code: 'Error code',
    quote: 'Got lost? No items here, but the 12-hour flash sale next door is worth a look.',
    quoteBy: '— Peak Mall curator',
  },

  shop: {
    notFoundTitle: 'Product not found',
    notFoundDesc: 'The product may be removed or the link is wrong.',
    shopAll: {
      title: 'All products',
      subtitle: 'Browse everything in the catalog',
      catAll: 'All',
      catElectronics: 'Electronics',
      catAppliances: 'Home appliances',
      sortDefault: 'Default',
      sortPriceAsc: 'Price ↑',
      sortPriceDesc: 'Price ↓',
      count: (n: number) => `${n} items`,
      searchPlaceholder: 'Search products',
      searchAria: 'Search products',
      sortAria: 'Sort by price',
      emptyTitle: 'No matching products',
      emptyDesc: 'Try a different keyword or category',
      discountBadge: '-60%',
      addToCart: 'Add to cart',
      wishAria: 'Add to wishlist',
    },
    shopNew: {
      title: 'New arrivals',
      subtitle: 'The latest additions to the catalog',
    },
    shopHot: {
      title: 'Hot sellers',
      subtitle: 'Best-selling picks this month',
    },
  },

  payRecords: {
    title: 'Payment records',
    sub: 'Demo only — every card here comes from the public test BIN list (no real cards).',
    nav: 'Payments',
    summaryAll: 'Records',
    summarySuccess: 'Successful',
    summaryFailed: 'Failed',
    summaryRefund: 'Refunded',
    summaryAmount: 'Captured',
    byBrand: 'By brand',
    byStatus: 'By status',
    byDay: 'Last 10 days',
    tableHead: {
      time: 'Paid at',
      orderId: 'Order ID',
      method: 'Method',
      brand: 'Brand',
      bin: 'BIN',
      last4: 'Last 4',
      amount: 'Amount',
      status: 'Status',
      authCode: 'Auth',
    },
    methodCard: 'Card',
    methodVisa: 'Visa',
    methodMastercard: 'Mastercard',
    errorCode: {
      INSUFFICIENT_FUNDS: 'Insufficient funds',
      CARD_DECLINED: 'Declined',
      EXPIRED: 'Expired',
      CVV_MISMATCH: 'CVV mismatch',
      NETWORK: 'Network error',
    },
    testBinTag: 'TEST BIN',
    legend: {
      test: 'Test card BIN',
      live: 'Live BIN (demo)',
    },
    export: 'Export CSV',
    exportNote: 'Public fields only: BIN / brand / last4 / amount / status / timestamp. Real card number, CVV, address and email are never exported.',
    exportDone: 'Exported',
    exportedRows: (n: number) => `Exported ${n} rows`,
    searchPlaceholder: 'Search order ID / BIN / last 4...',
    filterBrand: 'Brand',
    filterStatus: 'Status',
    filterAll: 'All',
    filterReset: 'Reset',
    emptyResult: 'No matching records',
    emptyResultDesc: 'Try clearing filters or adjusting the search keyword',
    showing: 'Showing',
    of: 'of',
    matched: 'matched',
    detail: {
      title: 'Payment detail',
      close: 'Close',
      copy: 'Copy auth code',
      copied: 'Copied',
      fields: {
        orderId: 'Order ID',
        method: 'Method',
        methodCard: 'Card',
        methodVisa: 'Visa',
        methodMastercard: 'Mastercard',
        brand: 'Brand',
        bin: 'BIN (first 6)',
        last4: 'Last 4',
        amount: 'Amount',
        currency: 'Currency',
        status: 'Status',
        authCode: 'Auth code',
        errorCode: 'Error code',
        paidAt: 'Paid at',
        relativeNow: 'ago',
      },
      notCopied: 'Copy failed — select the code manually',
      copiedToast: 'Auth code copied to clipboard',
    },
  },

  footer: {
    col1: 'Shop',
    col2: 'Account',
    col3: 'Help',
    col4: 'Contact',
    all: 'All products',
    new: 'New arrivals',
    hot: 'Best sellers',
    about: 'About us',
    orders: 'My orders',
    wishlist: 'My wishlist',
    address: 'Shipping address',
    aftersales: 'Returns & support',
    shipping: 'Shipping policy',
    terms: 'Terms of service',
    privacy: 'Privacy policy',
    account: 'Account',
    hours: (h: string) => `Hours: ${h}`,
    rights: 'All rights reserved',
  },
  legal: {
    termsTitle: 'Terms of service',
    privacyTitle: 'Privacy policy',
    lastUpdated: 'Last updated',
    termsSections: [
      { heading: 'Acceptance', body: 'By accessing or using Peak Mall you agree to these Terms of Service. If you disagree, stop using the service.' },
      { heading: 'Scope of service', body: 'Peak Mall is a demo static e-commerce prototype. All products, prices, and orders are fictional and do not represent real merchandise or transactions.' },
      { heading: 'Account responsibility', body: 'No signup is required. All state (cart, wishlist, address, orders) lives in your browser localStorage only and is never uploaded to a server.' },
      { heading: 'Prohibited use', body: 'Do not use this demo for any illegal activity, reverse-engineering, or malicious content injection.' },
      { heading: 'Disclaimer', body: 'This project is provided AS-IS with no warranty for any direct or indirect damages.' },
      { heading: 'Changes', body: 'We may update these terms at any time. Continued use means you accept the revised version.' },
    ],
    privacySections: [
      { heading: 'What we collect', body: 'This demo is a pure-frontend static site. The server records no personal data. All interaction state (cart, wishlist, address, orders) lives only in your browser localStorage.' },
      { heading: 'Cookies', body: 'We only use cookies/localStorage to remember your preferences (language, currency, UI settings). Never for tracking or advertising.' },
      { heading: 'Third-party services', body: 'Static files are hosted on Netlify. Netlify may collect basic access logs (e.g. IP), outside our control.' },
      { heading: 'Data export', body: 'You can wipe all local storage any time by clearing browser data.' },
      { heading: 'Contact', body: 'Questions: support@peakmall.com.' },
    ],
  },
  admin: {
    roleAdmin: 'Admin Console',
    roleAgent: 'Agent Console',
    roleFx: 'Affiliate',
    roleSwitchHint: 'Demo project: viewing the admin perspective. All data is localStorage mock.',
    loginTitle: 'Admin sign-in',
    loginIntro: 'Demo account. After signing in you enter the admin console. All data is localStorage mock and never sent to any real account.',
    loginUsername: 'Username',
    loginPassword: 'Password',
    loginSubmit: 'Sign in',
    loginHint: 'Demo account: admin · password: admin123',
    loginErrorEmpty: 'Please enter username and password',
    loginErrorBad: 'Wrong username or password',
    loginChecking: 'Checking…',
    logout: 'Sign out',
    gateChecking: 'Checking sign-in…',
    groupOverview: 'Overview',
    groupMall: 'Mall',
    groupDistribute: 'Distribution',
    groupFunds: 'Funds',
    groupTools: 'Tools',
    backToShop: 'Back to shop',
    resetData: 'Reset demo data',
    saved: 'Saved',
    dashboard: {
      title: 'Dashboard',
      kpiMembers: 'Members (affiliates + agents)',
      kpiMembersSub: (active: string, frozen: string) => `Active ${active} / Frozen ${frozen}`,
      kpiTotalOrder: 'Total order value',
      kpiTotalComm: 'Total commission paid',
      kpiToday: 'Today',
      kpiPendingWd: 'Pending withdrawals',
      pendingCount: (n: string) => `${n} requests`,
      // new KPIs
      kpiOrderCount: 'Order count',
      kpiPendingOrders: 'Pending payment',
      kpiShippable: 'Ready to ship',
      kpiOpenTickets: 'Open tickets',
      kpiGmv: 'Total GMV',
      kpi7dTrend: '7-day trend',
      // hints
      clickToOpen: 'Click to view →',
      // recent activity
      recentOrders: 'Recent orders',
      recentWd: 'Recent withdrawals',
      recentTickets: 'Recent tickets',
      emptyRecent: 'None',
      viewAll: 'View all',
      // system note
      systemNote: 'System note',
      systemNoteBody: 'This is the production build (Node + MySQL backend). All data is server-persistent; commissions are calculated server-side and cannot be tampered with locally.\nCommission engine: along the chain, agents earn at their own rate; a directly invited affiliate earns the first-tier rate the agent set (capped); everything else follows the global rule.',
    },
    products: {
      title: 'Products',
      count: (n: number) => `(${n} items)`,
      add: 'Add product',
      save: 'Save',
      on: 'On',
      off: 'Off',
      changeImg: 'Image',
      colName: 'Name',
      colCat: 'Category',
      colPrice: 'Price',
      colStock: 'Stock',
      colDesc: 'Description',
      colImg: 'Img',
      colStatus: 'Status',
      colAction: 'Action',
      empty: 'No products yet.',
      // detail modal
      detail: 'Product detail',
      detailEdit: 'Edit fields',
      detailCreatedAt: 'Listed at',
      detailTotalValue: 'Inventory value',
      detailCategory: 'Category',
      // bulk ops
      selectAll: 'Select all',
      bulkSelected: (n: number) => `${n} selected`,
      bulkOn: 'Bulk publish',
      bulkOff: 'Bulk unpublish',
      bulkClear: 'Clear selection',
      // delete
      delete: 'Delete',
      deleteTitle: 'Delete product',
      deleteBody: (n: number) => `Delete ${n} product${n > 1 ? 's' : ''}? This cannot be undone.`,
      deleteHint: 'Tip: unpublish keeps the record; delete removes it permanently.',
      confirmDelete: 'Confirm delete',
      // validation
      nameRequired: 'Name cannot be empty',
      priceInvalid: 'Price must be ≥ 0',
      stockInvalid: 'Stock must be ≥ 0',
      skuRequired: 'SKU is required',
      skuDuplicate: 'SKU already exists on another product',
      skuInvalid: 'SKU allows letters / digits / hyphens / underscores only',
      stockAlertInvalid: 'Stock alert must be ≥ 0',
      comparePriceInvalid: 'Compare price must be ≥ selling price',
      seoSlugInvalid: 'SEO slug allows lowercase letters / digits / hyphens only',
      // new fields
      colSku: 'SKU',
      colComparePrice: 'Compare',
      colCost: 'Cost',
      colStockAlert: 'Alert',
      colImages: 'Images',
      colSeoSlug: 'SEO slug',
      colUpdatedAt: 'Updated',
      detailSku: 'SKU',
      detailComparePrice: 'Compare price (optional)',
      detailCost: 'Cost (optional)',
      detailStockAlert: 'Stock alert (≤ triggers restock hint)',
      detailImages: 'Images (Enter to add, first is cover)',
      detailImagesPh: 'Emoji or image URL, then Enter',
      detailSeoSlug: 'SEO slug',
      detailSeoSlugHint: 'Optional · lowercase / digits / hyphens',
      detailDescPreview: 'Preview',
      detailDescEdit: 'Edit',
      // undo
      savedToast: 'Saved · product #{id}',
      undoCta: 'Undo',
      undoneToast: 'Change reverted',
    },
    orders: {
      title: 'Orders',
      tabs: { all: 'All', pending: 'Pending', paid: 'Paid', shipped: 'Shipped', completed: 'Completed', cancelled: 'Cancelled' },
      colOrder: 'Order #',
      colUser: 'User',
      colAmt: 'Amount',
      colStatus: 'Status',
      colPay: 'Method',
      colCard: 'Card',
      colContact: 'Contact',
      colAddr: 'Address',
      colTime: 'Time',
      colAction: 'Action',
      ship: 'Ship',
      complete: 'Complete',
      dash: '—',
      empty: 'No orders yet.',
      // detail modal
      detail: 'Order detail',
      detailTitle: 'Order information',
      paymentSection: 'Payment',
      shippingSection: 'Shipping',
      timelineSection: 'Timeline',
      cardBrand: 'Brand',
      cardLast4: 'Last 4',
      cardExpiry: 'Expires',
      payMethod: 'Method',
      markPaid: 'Mark paid',
      retryPay: 'Retry payment',
      // actions
      refund: 'Refund',
      cancel: 'Cancel order',
      // bulk
      selectAll: 'Select all',
      bulkSelected: (n: number) => `${n} selected`,
      bulkShip: 'Bulk ship',
      bulkComplete: 'Bulk complete',
      bulkCancel: 'Bulk cancel',
      bulkClear: 'Clear',
      delete: 'Delete',
      // cancel / refund modal
      cancelTitle: 'Cancel order',
      cancelBody: (n: number) => `Cancel ${n} order${n > 1 ? 's' : ''}? This cannot be undone.`,
      cancelReasonLabel: 'Cancel reason',
      cancelReasonPh: 'Optional — tell the user why',
      confirmCancel: 'Confirm cancel',
      refundTitle: 'Refund',
      refundBody: (amtText: string, name: string) => `Refund the full ${amtText} for order ${name}? This cannot be undone.`,
      confirmRefund: 'Confirm refund',
      deleteTitle: 'Delete order',
      deleteBody: (n: number) => `Delete ${n} order${n > 1 ? 's' : ''}? This cannot be undone.`,
      deleteHint: 'Tip: cancel keeps the record; delete removes it permanently.',
      confirmDelete: 'Confirm delete',
      // timeline
      evtCreated: 'Order placed',
      evtPaid: 'Payment received',
      evtShipped: 'Shipped',
      evtCompleted: 'Completed',
      evtCancelled: 'Cancelled',
      evtRefunded: 'Refunded',
    },
    users: {
      title: 'Affiliates / Agents',
      add: 'Add',
      colRole: 'Role',
      colRoleAgent: 'Agent',
      colRoleFx: 'Affiliate',
      colReferrer: 'Referrer',
      colTeam: 'Team',
      colBal: 'Balance',
      colStatus: 'Status',
      colReg: 'Joined',
      colTrc20: 'TRC-20 address',
      colAction: 'Action',
      statusActive: 'Active',
      statusFrozen: 'Frozen',
      freeze: 'Freeze',
      unfreeze: 'Unfreeze',
      resetPwd: 'Reset pwd',
      empty: 'No users yet.',
      // detail modal
      detail: 'Member detail',
      detailTitle: 'Member information',
      basicSection: 'Account',
      financeSection: 'Finance',
      recentOrdersSection: 'Recent orders',
      recentOrdersEmpty: 'No orders for this member',
      viewAllOrders: 'View all orders for this member',
      roleAgent: 'Agent',
      roleFx: 'Affiliate',
      changeRole: 'Switch role',
      // bulk
      selectAll: 'Select all',
      bulkSelected: (n: number) => `${n} selected`,
      bulkFreeze: 'Bulk freeze',
      bulkUnfreeze: 'Bulk unfreeze',
      bulkClear: 'Clear',
      delete: 'Delete',
      // delete
      deleteTitle: 'Delete member',
      deleteBody: (n: number) => `Delete ${n} member${n > 1 ? 's' : ''}? This cannot be undone.`,
      deleteHint: 'Tip: freeze keeps the record; delete removes it permanently.',
      confirmDelete: 'Confirm delete',
    },
    agents: {
      title: 'Agents — rate adjustment',
      hint: 'own_rate: agent\u2019s own commission rate (overrides global); sub_rate: first-tier rate the agent can offer their direct invitees; sub_rate_limit: cap on the sub_rate (enforced server-side).',
      colOwn: 'Own rate',
      colSub: 'Sub rate',
      colLimit: 'Sub rate cap',
      colTrc20: 'TRC-20 address',
      colAction: 'Action',
      save: 'Save',
      empty: 'No agents yet.',
      saved: 'Saved',
      copyAddress: 'Copy address',
      copied: 'Copied',
      copyErr: 'Copy failed',
      savedToast: 'Saved · agent #{id}',
      undoCta: 'Undo',
      undoneToast: 'Change reverted',
    },
    invite: {
      title: 'Invite codes',
      add: 'Generate code',
      colCode: 'Code',
      colUsed: 'Used / limit',
      colStatus: 'Status',
      colTime: 'Created',
      colAction: 'Action',
      disable: 'Disable',
      enable: 'Enable',
      empty: 'No invite codes yet.',
    },
    tickets: {
      title: 'After-sales',
      colOrder: 'Order #',
      colUser: 'User',
      colReason: 'Reason',
      colStatus: 'Status',
      colTime: 'Time',
      colAction: 'Action',
      reply: 'Reply',
      close: 'Close',
      empty: 'No tickets yet.',
      // detail modal
      detail: 'Ticket detail',
      detailTitle: 'Ticket information',
      orderSection: 'Order',
      contentSection: 'Reason',
      replySection: 'Agent reply',
      replyPh: 'Type your reply. Saving auto-moves the ticket to Replied.',
      noReply: 'Not replied yet',
      replySavedAt: (t: string) => `Replied at ${t}`,
      // status
      statusOpen: 'Open',
      statusReplied: 'Replied',
      statusClosed: 'Closed',
      // bulk
      selectAll: 'Select all',
      bulkSelected: (n: number) => `${n} selected`,
      bulkReply: 'Bulk reply',
      bulkClose: 'Bulk close',
      bulkClear: 'Clear',
    },
    rules: {
      title: 'Commission rules',
      ownRate: 'Self-purchase rate (%)',
      minWd: 'Min withdrawal',
      fee: 'Withdrawal fee (%)',
      mode: 'Settlement mode',
      modeVal: 'Self-purchase only (only the buyer\u2019s own commission is settled)',
      hint: 'Tier-2 and tier-3 commissions are disabled; only the buyer\u2019s own commission is settled.',
      commissionOn: 'Enable commission settlement',
      autoApprove: 'Auto-approve withdrawals',
      saveAll: 'Save all',
    },
    comm: {
      title: 'Commission ledger',
      colUser: 'User',
      colAmt: 'Amount',
      colSource: 'Source order',
      colRate: 'Rate',
      colStatus: 'Status',
      colTime: 'Time',
      settled: 'Settled',
      pending: 'Pending',
      empty: 'No ledger entries yet.',
    },
    wd: {
      title: 'Withdrawal review',
      colId: 'ID',
      colUser: 'User',
      colAmt: 'Amount',
      colFee: 'Fee',
      colMethod: 'Method',
      colReject: 'Reject reason',
      colStatus: 'Status',
      colTime: 'Time',
      colProcessed: 'Processed at',
      colAddr: 'Bound TRC-20',
      colAction: 'Action',
      approve: 'Approve',
      reject: 'Reject',
      markPaid: 'Mark paid',
      view: 'View',
      unbound: 'Not bound',
      addrMismatch: '⚠ Mismatched address',
      empty: 'No records yet.',
      rejectTitle: 'Reject this withdrawal',
      rejectReasonLabel: 'Reject reason',
      rejectReasonPh: 'Tell the user why this is rejected (saved on the order).',
      rejectReasonRequired: 'A reject reason is required.',
      cancel: 'Cancel',
      confirmReject: 'Confirm reject',
      approveTitle: 'Confirm approval',
      approveBodyApprove: 'Approving will move this request to Approved. The user can then wait for the payout.',
      approveBodyPay: 'Marking as paid will deduct the requested amount from the user balance.',
      approveNetLabel: 'Net payout',
      approveFeeLabel: 'Fee',
      confirmApprove: 'Confirm approve',
      confirmPay: 'Confirm paid',
      paidTitle: 'Confirm payout',
      paidBody: 'This will mark the request as paid and deduct the amount from the user balance.',
    },
    wdCenter: {
      title: 'Withdrawals',
      tabs: { all: 'All', pending: 'Pending', approved: 'Approved', rejected: 'Rejected', paid: 'Paid' },
      colId: 'ID',
      colAmt: 'Amount',
      colFee: 'Fee',
      colMethod: 'Method',
      colAccount: 'Account',
      colStatus: 'Status',
      colReject: 'Reject reason',
      colTime: 'Time',
      colAction: 'Action',
      apply: 'Apply',
      balance: 'Available',
      min: 'Min',
      empty: 'No withdrawals yet.',
      applySuccess: 'Submitted. Waiting for admin review.',
      applyFailMin: 'Amount is below the minimum.',
      applyFailInsufficient: 'Insufficient available balance.',
      applyFailAddr: 'Bind a TRC-20 address before USDT withdrawals.',
      submitted: 'Submitted',
      accountLabel: 'Destination address / account',
      accountPh: 'TRC-20 address or card number',
      insufficientBalance: 'Insufficient',
      needBind: 'Address required',
      currentUserLabel: 'Current account',
      switchUser: 'Switch demo user',
    },
    home: {
      title: 'Home settings',
      heroTitle: 'Hero title',
      heroSub: 'Hero subtitle / slogan',
      notice: 'Notice (leave empty to hide)',
      hint: 'Hero title overrides the first-screen H1; subtitle is shared with the recommendations section and footer; the notice appears in the marquee under the hero.',
      save: 'Save',
      preview: 'Preview',
      phTitle: 'Global curated picks',
      phSub: 'Official sourcing · Authenticity guaranteed · Multi-warehouse',
      phNotice: 'New user gift · Authenticity guaranteed',
    },
    support: {
      title: 'Support widget',
      name: 'Name',
      url: 'Telegram URL',
      hours: 'Hours',
      save: 'Save',
      preview: 'Preview',
      phUrl: 'https://t.me/YourChannel',
      phHours: '13:00 - 23:30',
      hintUrl: 'Full URL, e.g. https://t.me/MementoCare',
      hintHours: 'Leave empty to hide the hours line',
    },
    demo: {
      title: 'Demo order',
      hint: 'Trigger a fake order in this demo to see order management and withdrawal review populate.',
      trigger: 'Create an order',
      lastOrder: 'Last created',
      none: 'None yet',
    },
  },
} as const;