/**
 * 集中文案表 - 替代散落的 [COPY:xxx] 占位
 *
 * 红线:本文案基于参考站结构改写,不直接复用源站字
 * 每条都要过一遍:
 *   1. 不抄原表述
 *   2. 不抄具体金额/折扣/优惠条件
 *   3. 不实现强制邀请码/分销/提现
 *
 * 改了这里,所有组件 / 页面会同步生效
 */

export const COPY = {
  brand: {
    name: '顶峰商城',
    slogan: 'PEAK MALL',
    intro: '全球优选 · 正品保障。28 国配送,7 天无理由退换。',
    shortName: '顶峰',
  },

  nav: {
    home: '首页',
    all: '全部',
    new: '新品',
    hot: '热卖',
    orders: '我的订单',
    after: '售后',
    about: '关于',
  },

  currencyLabel: {
    USD: 'USD 美元',
    CNY: 'CNY 人民币',
    EUR: 'EUR 欧元',
    GBP: 'GBP 英镑',
    JPY: 'JPY 日元',
    KRW: 'KRW 韩元',
    AUD: 'AUD 澳元',
    CAD: 'CAD 加元',
  },

  /** G3: fx 汇率换算器 + 历史图表 */
  fx: {
    title: '汇率换算',
    subtitle: '实时汇率换算 + 7 天走势',
    convertTitle: '汇率换算',
    amount: '金额',
    from: '从',
    to: '到',
    result: '结果',
    rate: '当前汇率',
    historyTitle: '7 天走势',
    historyRange: '范围',
    range7d: '7 天',
    range30d: '30 天',
    ratesTitle: '主要汇率',
    noChange: '持平',
    upLabel: '涨',
    downLabel: '跌',
    lastUpdate: '更新于',
  },

  langLabel: { zh: '中文', en: 'EN' },

  sync: {
    title: '同步失败',
    addToCart: '加入购物车失败,已恢复原状态',
    updateQty: '更新数量失败,已恢复原状态',
    removeFromCart: '删除商品失败,已恢复原状态',
    clearCart: '清空购物车失败,已恢复原状态',
    toggleSelect: '选择状态同步失败',
    setAllSelected: '全选状态同步失败',
    toggleWish: '收藏状态同步失败',
    cancelOrder: '取消订单失败,已恢复原状态',
    placeOrder: '订单同步到服务器失败,请稍后重试',
  },

  header: {
    welcome: '您好,欢迎来到顶峰',
    login: '登录 / 注册',
    searchAria: '站内搜索',
    inputAria: '搜索商品',
    submit: '搜索',
    orderStatus: '订单状态',
    logout: '退出',
    logoutAria: '退出登录',
    /** S1: 搜索建议下拉 */
    sugHistory: '最近搜索',
    sugHot: '热门分类',
    sugEmpty: '暂无搜索建议',
    sugClear: '清空',
    sugNoHistory: '暂无搜索历史',
    clear: '清空',
    /** S2: 移动端搜索条 */
    mobileSearchOpen: '打开搜索',
    mobileSearchClose: '关闭搜索',
    /** S4: 全局快捷键提示 */
    shortcutHint: '⌘K',
    shortcutHintLabel: '按 ⌘K 快速搜索',
    /** S5: 拼写纠错 */
    didYouMean: '你是不是想搜',
    didYouMeanSuffix: '？',
  },

  announcement: {
    defaultTag: '公告',
    defaultText: '全场满 $50 包邮 · 7 天无理由退换',
  },

  card: {
    wishlistOn: '♥',
    wishlistOff: '♡',
    addedToCart: '✓ 已加入',
  },

  modal: {
    close: '关闭',
    closeSymbol: '✕',
    coverEmoji: '📦',
  },

  auth: {
    loginTitle: '登录顶峰',
    loginSub: '使用邮箱与密码登录',
    registerTitle: '注册新账户',
    registerSub: '加入 10 万+ 满意用户',
    hero: '欢迎来到顶峰',
    login: '登录账户',
    register: '注册新账户',
    email: '邮箱',
    emailPh: 'you@example.com',
    password: '密码',
    passwordPh: '至少 8 位',
    password2: '确认密码',
    password2Ph: '再输入一次',
    nickname: '昵称',
    nicknamePh: '选一个好记的',
    invite: '邀请码',
    invitePh: '可选',
    remember: '记住我',
    pwMismatch: '两次密码不一致',
    errGeneric: '出错了,请稍后再试',
    announce: '登录后享受会员价 · 历史订单随时查',
    loginErrorShort: '密码至少 6 位',
    registerErrorShort: '密码至少 6 位',
    loginErrorGeneric: '登录失败',
    registerErrorGeneric: '注册失败',
    loggedInAs: (email: string, at: string) => `已登录为 ${email} · 登录于 ${at}`,
    // Phase 2.5 — legal consent. The {terms} / {privacy} placeholders
    // are replaced by the AuthSplit component with linked anchors.
    consentLabel: '我已阅读并同意 {terms} 和 {privacy}',
    termsLinkText: '《使用条款》',
    privacyLinkText: '《隐私政策》',
    consentRequired: '请勾选同意《使用条款》和《隐私政策》后继续',
    // v40: 登录/管理后台合页 — tab 切换
    tabUser: '用户登录',
    tabAdmin: '管理员登录',
    adminPanelTitle: '管理员通道',
    adminPanelSub: '管理员账号在 Supabase Auth 中授予。请联系运维或在 SQL 中将 role 更新为 admin。',
    switchToAdmin: '管理员入口 →',
    switchToUser: '← 用户登录',
  },
  cta: {
    addToCart: '加入购物车',
    buyNow: '立即购买',
    viewDetail: '查看详情',
    backToHome: '返回首页',
    goLogin: '去登录',
    goRegister: '去注册',
    subscribe: '立即订阅',
    emailPh: '输入邮箱地址',
    emailLabel: '邮箱地址',
    label: '限时福利',
    title: '订阅获取专属折扣',
    sub: '新用户首单立享额外优惠 · 每周精选商品推荐 · 随时退订',
    success: '订阅成功!请在邮箱中查收欢迎邮件。',
    error: '请输入有效的邮箱地址。',
    disclaimer: '我们尊重您的隐私,可随时退订。详情请见《隐私政策》。',
  },
  label: {
    inStock: '现货',
    outOfStock: '缺货',
    pcs: '件',
    price: '价格',
    category: '分类',
    stock: '库存',
    createdAt: '上架时间',
    noDescription: '暂无详细描述',
  },
  service: {
    shipping: { title: '多仓直发', desc: '全球 28 国配送' },
    return: { title: '退换无忧', desc: '7 天无理由' },
    support: { title: '精致服务', desc: '13:00-23:30 在线' },
    authentic: { title: '正品保障', desc: '假一赔十' },
  },
  footer: {
    col1: '购物',
    col2: '账户',
    col3: '帮助',
    col4: '联系',
    all: '全部商品',
    new: '新品上架',
    hot: '热卖榜单',
    about: '关于我们',
    orders: '我的订单',
    wishlist: '我的收藏',
    address: '收货地址',
    aftersales: '售后服务',
    shipping: '配送说明',
    terms: '使用条款',
    privacy: '隐私政策',
    account: '个人中心',
    hours: (h: string) => `服务时间: ${h}`,
    rights: '保留所有权利',
  },
  product: {
    spec: '规格参数',
    rating: '用户评分',
    related: '看了又看',
    qty: '数量',
    addSuccess: '已加入购物车',
    loginRequired: '请先登录',
    featuresLabel: '产品亮点',
    specsLabel: '规格参数',
    reviewsLabel: '用户评价',
    shippingLabel: '配送与退换',
    inStockShort: '现货',
    soldLabel: '已售',
    skuLabel: '编号',
    categoryLabel: '分类',
    addedOnLabel: '上架',
    freeShipNote: '满 $50 全球包邮 · 7 天无理由退换',
    reviewsSummary: (n: number) => `基于 ${n} 条真实用户评价`,
    /** v29: 详情丰满化 */
    highlightsLabel: '核心亮点',
    specsGroupBase: '基础信息',
    specsGroupPerf: '性能与存储',
    specsGroupDisplay: '显示与音频',
    specsGroupBattery: '电池与散热',
    specsGroupPorts: '接口与连接',
    specsGroupPackage: '包装与售后',
    faqLabel: '常见问题',
    reviewSortLabel: '排序',
    reviewSortLatest: '最新',
    reviewSortHelpful: '最有帮助',
    reviewSortRatingDesc: '评分 ↓',
    reviewHelpfulBtn: '有帮助',
    reviewHelpfulCount: (n: number) => `${n} 人觉得有帮助`,
    reviewFilterAll: '全部',
    reviewFilterWithPic: '带图',
    reviewFilterFiveStar: '5 星',
    reviewFilterFourStar: '4 星',
    reviewFilterVerified: '已购',
    reviewEmptyTitle: '暂无该筛选下的评价',
    reviewEmptyDesc: '试试切换其他条件,或全部评价中浏览',
    faqShipping: '多久能到货?',
    faqShippingA: '海外仓直发,工作日 48 小时内出库,预计 3–7 天送达 28 国。',
    faqReturn: '支持 7 天无理由退换吗?',
    faqReturnA: '支持。7 天内不满意可申请退货,运费由我方承担,款项原路退回。',
    faqWarranty: '数码商品保修多久?',
    faqWarrantyA: '主机 1 年免费保修,电池单独 6 个月。凭订单号即可就近维修点受理。',
    faqInvoice: '可以开具发票吗?',
    faqInvoiceA: '下单时备注公司抬头与税号,可在订单详情页申请电子发票,15 个工作日内开具。',
    faqOverseas: '海外可以使用吗?键盘布局?',
    faqOverseasA: '支持英文 / 中文 / 日文 / 韩文输入法切换,出厂默认美式键盘布局,贴膜附赠。',
    faqBulk: '公司批量采购有优惠吗?',
    faqBulkA: '10 台起联系企业客服,可享团购价与定制配置,30 台以上支持开具增值税专票。',
    /** v30: 右侧信息栏深度 */
    flashSaleTitle: '限时优惠',
    flashSaleEndsIn: '距结束',
    soldProgress: (sold: number, stock: number) => `已售 ${sold} · 库存仅剩 ${stock} 件`,
    stockLowHint: '库存紧张',
    stockLowUnit: '件',
    colorLabel: '颜色',
    colorGray: '深空灰',
    colorSilver: '银河银',
    sizeLabel: '容量',
    size512: '512GB',
    size1tb: '1TB · 加 $99',
    guaranteeTitle: '服务保障',
    guarantee7day: '7 天无理由退换',
    guarantee7dayDesc: '不满意 7 天内可申请退货,运费我方承担,款项原路退回。',
    guaranteeAuth: '正品保障',
    guaranteeAuthDesc: '官方授权渠道供货,提供原厂发票与正品验证。',
    guaranteeShip: '海外仓直发',
    guaranteeShipDesc: '28 国本地仓库,48h 内出库,3–7 个工作日送达。',
    guaranteeWarranty: '一年保修',
    guaranteeWarrantyDesc: '主机 1 年 · 电池 6 个月,全国 28 城上门服务。',
    expandMore: '查看详情',
    expandLess: '收起',
    selectVariantHint: '请选择规格',
    saleBadge: '限时折扣',
    /** v30: 图文视频 + 对比表 */
    productVideoLabel: '产品视频',
    playVideo: '播放',
    productShowcaseLabel: '产品图集',
    compareLabel: '同价位对比',
    compareThisRow: '本款',
    compareOther: '他款',
    /** v31: 互动深度 — Q&A + 楼中楼 + 图片墙 */
    qaTitle: '商品问答',
    qaSubtitle: '买前问,已买答,官方入驻解答',
    qaAllFilter: '全部',
    qaUnansweredFilter: '待解答',
    qaAskBtn: '我要提问',
    qaAskTitle: '发表问题',
    qaPlaceholder: '说说你最关心的细节,比如兼容、尺寸、使用场景…',
    qaSubmitBtn: '发布问题',
    qaCancelBtn: '取消',
    qaCharLimit: (n: number) => `${n}/200 字`,
    qaEmptyTitle: '暂无问题',
    qaEmptyDesc: '试试换一个筛选,或在右侧提问',
    qaSellerBadge: '官方',
    qaHelpfulBtn: '有帮助',
    qaHelpfulCount: (n: number) => `${n} 人觉得有帮助`,
    qaAnswerBtn: '写回答',
    qaAnswerPlaceholder: '写出你的经验,限 300 字',
    qaAnswerSubmit: '提交回答',
    qaAskNameLabel: '署名',
    qaAskNamePlaceholder: '昵称或匿名',
    replyTitle: '卖家回复',
    replyPlaceholder: '写下官方回答,买家可以看到',
    replySubmit: '提交回复',
    replyHelpfulBtn: '这条回复有帮助',
    photoWallLabel: '买家的实拍图',
    photoWallCount: (n: number) => `共 ${n} 张买家实拍`,
    photoWallEmpty: '还没有买家的实拍图',
    photoWallFilter: '全部',
  },
  hero: {
    h1: '精选全球好物',
    h2: '品质生活 一站即达',
    sub: '数码电子 · 智能家居 · 28 国直邮 · 7 天无理由退换',
    eyebrow: '限时活动 · 全场满 $50 包邮',
    ctaPrimary: '立即选购',
    ctaSecondary: '查看热卖',
    socialProof: '10 万 + 用户的选择',
    rating: '4.9 / 5.0',
    floatingCard1: '已发货',
    floatingCard1Sub: '预计 3 天到达',
    floatingCard2: '购买体验非常好,客服响应快,物流准时!',
    searchPlaceholder: '搜索 16 万件好物 · 笔记本 / 耳机 / 扫地机 …',
    searchHint: '热门:',
    searchTags: ['商务本', '真无线耳机', '扫地机器人', '智能手表'],
    trust: {
      countries: '覆盖国家',
      countryUnit: '+',
      support: '在线客服',
      supportUnit: '',
      return: '无理由退换',
      returnUnit: '天',
      authentic: '正品保障',
      authenticUnit: '',
    },
  },
  home: {
    browseByCat: '分类浏览',
    exploreCategories: '探索精选分类',
    cat1Desc: '从商务本到智能穿戴,覆盖数字生活每一面',
    cat2Desc: '智能家居升级,让日常更轻松更高效',
    catOfItems: (n: number) => `${n} 件好物`,
    cat1: '数码电子',
    cat2: '家用电器',
  },
  flashSale: {
    label: '限时秒杀',
    title: '12 小时限时折扣',
    scope: '全场通用 · 仅此一波',
    endsIn: '距结束',
    stock: '剩余库存',
    save: '立省',
  },
  topSelling: {
    label: '本周热销榜',
    title: 'TOP 5 用户最爱',
    viewAll: '查看完整榜单',
    sold: '已售',
  },
  rec: {
    label: '为您推荐',
    title: '精选推荐',
    sub: '基于浏览历史与热销数据智能推荐',
    sortBy: '排序',
    sortDefault: '综合排序',
    sortPriceAsc: '价格从低到高',
    sortPriceDesc: '价格从高到低',
    sortRating: '好评优先',
    empty: '该分类暂无商品,试试其他分类',
  },
  quality: {
    label: '品质专区',
    title: '两大精选系列',
    collection: '精选系列',
    cat1: '数码电子',
    cat2: '家用电器',
    b1Title: '数码旗舰专区',
    b1Sub: '从商务办公到日常娱乐,旗舰品质,全球优选',
    b1Bullets: ['商务本 · 旗舰性能', '智能穿戴 · 健康追踪', '音频 · 沉浸体验'],
    b1Cta: '进入数码',
    b2Title: '智能家居专区',
    b2Sub: '科技点亮生活,让日常家务更轻松',
    b2Bullets: ['扫地机器人 · LiDAR 导航', '智能音箱 · 语音控制', '安防监控 · 24h 守护'],
    b2Cta: '进入家居',
  },
  newArrivals: {
    label: '新品上市',
    title: '刚上架 · 抢先看',
    viewAll: '查看全部新品',
    badge: 'NEW',
    hot: '首发',
  },
  testimonial: {
    label: '真实评价',
    title: '听听他们怎么说',
    aggregate: '4.9 · 来自 10,000+ 用户',
    q1: '第一次在顶峰商城购物,体验超出预期。包装严实,发货速度很快,商品质量也对得起价格。',
    n1: '陈女士',
    r1: '北京 · 数码爱好者',
    q2: '买了商务本和真无线耳机,都是正品,价格比专柜便宜不少。客服回复也很专业。',
    n2: '李先生',
    r2: '上海 · 商务人士',
    q3: '智能家居系列质量不错,扫地机器人很智能,APP 控制也很流畅。已经回购了三次。',
    n3: '王女士',
    r3: '深圳 · 设计师',
  },
  promise: {
    label: '我们的承诺',
    title: '四大保障,买得放心',
  },
  shop: {
    notFoundTitle: '商品不存在',
    notFoundDesc: '商品可能已下架,或链接有误。',
    shopAll: {
      title: '全部商品',
      subtitle: '浏览商城全部上架好物',
      catAll: '全部',
      catElectronics: '数码电子',
      catAppliances: '家用电器',
      sortDefault: '默认排序',
      sortPriceAsc: '价格 ↑',
      sortPriceDesc: '价格 ↓',
      count: (n: number) => `共 ${n} 件商品`,
      searchPlaceholder: '搜索商品名称',
      searchAria: '搜索商品',
      sortAria: '价格排序',
      emptyTitle: '没有匹配的商品',
      emptyDesc: '换个关键词或分类试试',
      discountBadge: '-60%',
      addToCart: '加入购物车',
      wishAria: '加入收藏',
    },
    shopNew: {
      title: '新品上架',
      subtitle: '最新上架的商品一览',
    },
    shopHot: {
      title: '人气热卖',
      subtitle: '本月销量最高的爆款好物',
    },
  },
  cart: {
    title: '我的购物车',
    empty: '购物车是空的',
    emptyDesc: '去看看有什么好物吧',
    total: '合计',
    checkout: '去结算',
    clear: '清空购物车',
    continue: '继续购物',
    qty: '数量',
    subtotal: '小计',
    orderPlaced: '订单已生成',
    orderPlacedDesc: '请在“我的订单”中查看状态',
    removed: '已移除',
    freeShippingNote: '免运费',
    shippingFee: '$5.00',
    shippingLabel: '运费',
    qtyDecLabel: '减少数量',
    qtyIncLabel: '增加数量',
    /** A1: 单品勾选 */
    selectAll: '全选',
    selectedCount: (n: number, total: number) => `已选 ${n}/${total} 件`,
    selectedEmpty: '请勾选要结算的商品',
    /** A2: 优惠券 */
    couponTitle: '优惠码',
    couponPlaceholder: '输入优惠码',
    couponApply: '使用',
    couponRemove: '移除',
    couponApplied: (code: string) => `已使用 ${code}`,
    couponInvalid: '优惠码无效或已过期',
    couponInvalidMin: '满 $200 可用',
    /** 折扣明细行 */
    discountLabel: '优惠折扣',
    /** 可用优惠码提示 */
    couponHints: '试试 SAVE10 (9 折) / FREESHIP (免运费) / VIP20 (满 $200 减 $20)',
    /** G1: 上次优惠码复用 */
    lastCoupon: (code: string) => `上次用过 ${code}`,
    lastCouponReuse: '再次使用',
  },

  search: {
    title: '搜索结果',
    subCount: (n: number, q: string) => `共 ${n} 件商品匹配“${q}”`,
    subEmpty: (q: string) => `未找到匹配“${q}”的商品`,
    suggest: '试试其他关键词，或返回首页继续逛逛',
    clear: '清空',
    backHome: '返回首页',
    hot: '热门关键词',
    hotTags: ['笔记本', '耳机', '扫地机器人', '智能手表', '加湿器'],
  },
  orders: {
    title: '我的订单',
    empty: '暂无订单',
    emptyDesc: '下单后会显示在这里',
    startShopping: '去购物',
    itemCount: (n: number) => `${n} 件商品`,
    orderId: '订单号',
    placedAt: '下单时间',
    status: '状态',
    amount: '金额',
    viewDetail: '查看详情',
    statusPending: '待支付',
    statusPaid: '已支付',
    statusShipped: '已发货',
    statusDelivered: '已签收',
    /** A3: tab + search */
    tabAll: '全部',
    tabPending: '待支付',
    tabPaid: '已支付',
    tabShipped: '已发货',
    tabDelivered: '已签收',
    tabCancelled: '已取消',
    searchPlaceholder: '搜索订单号 / 商品名',
    searchAria: '搜索订单',
    noMatch: '没有匹配的订单',
    noMatchDesc: '试试调整搜索词或切换状态',
    /** A4: cancel / buy again */
    cancel: '取消订单',
    cancelConfirm: '确定取消该订单?',
    cancelHint: '取消后该订单状态会变为「已取消」,此操作不可撤销。',
    cancelled: '已取消',
    buyAgain: '再买一次',
    buyAgainOk: '已加入购物车,跳转到购物车…',
    cancelledTag: '已取消',
    /** A5: order detail expand */
    hideDetail: '收起详情',
    payment: '支付方式',
    paymentNone: '未支付',
    paymentBrand: (b: string) => `${b}`,
    paymentLast4: (n: string) => `•••• ${n}`,
    paymentAuth: (a: string) => `授权码 ${a}`,
    cancelledAt: '取消时间',
    timeline: '订单时间线',
    timelinePlaced: '已下单',
    timelinePaid: '已支付',
    timelineShipped: '已发货',
    timelineDelivered: '已签收',
    timelineCancelled: '已取消',
  },
  profile: {
    title: '个人中心',
    notLoggedIn: '请先登录后查看个人中心',
    goLogin: '去登录',
    nickname: '昵称',
    email: '邮箱',
    edit: '编辑',
    myOrders: '我的订单',
    myWishlist: '我的收藏',
    cart: '购物车',
    settings: '账户设置',
    logout: '退出登录',
    memberSince: '加入时间',
  },
  userSidebar: {
    groupMall: '商城',
    groupDistribute: '分销业务',
    groupAccount: '账户',
    groupMine: '我的',
    navShopHome: '商城首页',
    navShopAll: '全部商品',
    navShopNew: '最新商品',
    navShopHot: '热卖爆款',
    navCart: '购物车',
    navMyOrders: '我的订单',
    navMyAccount: '我的账户',
    navCommissions: '佣金明细',
    navWithdraw: '提现中心',
    navWithdrawAddr: '绑定提现地址',
    navPersonalCenter: '个人中心',
    navChangePassword: '修改密码',
    navFundPassword: '资金密码',
    navMyAddress: '我的地址',
    navMyWishlist: '我的收藏',
    navMyAftersale: '我的售后',
    logout: '退出登录',
  },
  wishlist: {
    title: '我的收藏',
    empty: '还没有收藏任何商品',
    emptyDesc: '在心形按钮上点击,把喜欢的商品加入这里',
    addToCart: '加入购物车',
    removeAll: '清空收藏',
    addedAt: '收藏于',
  },
  address: {
    title: '我的地址',
    empty: '还没有保存地址',
    emptyDesc: '添加收货地址,下单时自动填充',
    addNew: '新增地址',
    edit: '编辑',
    remove: '删除',
    setDefault: '设为默认',
    default: '默认',
    name: '收货人',
    phone: '手机号',
    phonePh: '11 位手机号,如 13800001234',
    phoneInvalid: '请输入有效的 11 位手机号(1[3-9] 开头)',
    region: '省市区',
    detail: '详细地址',
    save: '保存',
    cancel: '取消',
    removeConfirm: '确定删除该地址吗?',
    removeHint: '该地址将从你的收货地址簿中移除,此操作不可撤销。',
    removed: '地址已删除',
    /** D4: tag selector + form errors */
    tag: '标签',
    tagHome: '家',
    tagOffice: '公司',
    tagOther: '其他',
    nameRequired: '请填写收货人姓名',
    savedFlash: '地址已保存',
  },
  checkout: {
    title: '确认订单',
    subtitle: '选择收货地址与支付方式',
    sectionAddress: '收货地址',
    noAddress: '还没有收货地址',
    noAddressDesc: '请先到地址簿添加',
    goAddresses: '去添加地址',
    sectionPayment: '支付方式',
    methodCard: '银行卡',
    methodCardDesc: '推荐 — 3D Secure 验证',
    methodVisa: 'Visa 卡支付',
    methodVisaDesc: '推荐 — 3D Secure 验证',
    methodMastercard: 'Mastercard 卡支付',
    methodMastercardDesc: '推荐 — 3D Secure 验证',
    sectionSummary: '订单总览',
    itemCount: (n: number) => `${n} 件商品`,
    subtotal: '商品小计',
    shipping: '运费',
    freeShipping: '免运费',
    total: '应付总额',
    placeOrder: '提交订单',
    placeOrderNeedAddress: '请先选择或添加收货地址',
    orderSuccess: '订单已生成',
    orderSuccessDesc: '请在“我的订单”中查看状态',
    selectDefault: '使用默认地址',
    /** 收银台 */
    cashier: '收银台',
    cashierSubtitle: '请选择支付方式',
    payBy: '请选择支付方式',
    cardNumber: '卡号',
    cardNumberPh: '4242 4242 4242 4242',
    cardExp: '有效期 (MM/YY)',
    cardExpPh: '08/29',
    cardCvv: 'CVV',
    cardCvvPh: '123',
    cardHolder: '持卡人姓名',
    cardHolderPh: '与卡面一致',
    cardEncrypted: '信息经加密传输,仅记录卡号后 4 位与品牌用于对账',
    brandDetected: (b: string) => `已识别 ${b}`,
    brandUnknown: '请输入有效卡号',
    // Phase 2.5 — checkout-time Terms consent (single checkbox; Privacy is
    // referenced via the same anchored link as the registration panel).
    termsAgree: '我已阅读并同意 {terms}',
    termsAgreeRequired: '请先勾选同意《使用条款》后提交订单',
    termsLinkText: '《使用条款》',
    privacyLinkText: '《隐私政策》',
    confirmPay: '确认支付',
    payFailed: '支付失败,请重试或换其他方式',
    payProcessing: '支付处理中…',
  },
  aftersale: {
    title: '我的售后',
    tabAll: '全部',
    empty: '没有售后记录',
    emptyDesc: '订单有售后需求时可在此发起申请',
    requestBtn: '申请售后',
    orderId: '订单号',
    reason: '原因',
    statusPending: '待处理',
    statusApproved: '已通过',
    statusRejected: '已拒绝',
    statusCompleted: '已完成',
    statusRefunded: '已退款',
    note: '说明',
    submitOk: '售后申请已提交',
    viewOrder: '查看订单',
    /** G2: detail modal */
    detailTitle: '售后详情',
    timelineTitle: '处理进度',
    stepSubmitted: '已提交申请',
    stepReviewing: '客服审核中',
    stepApproved: '审核通过',
    stepDone: '处理完成',
    closeBtn: '关闭',
    createdAt: '申请时间',
    expectTime: '预计 24 小时内回复',
    refundAmount: '退款金额',
    refundMethod: '退款方式',
    refundToOrigin: '原支付方式退回',
    contactCs: '联系客服',
  },
  about: {
    title: '关于峰峰商城',
    subtitle: '全球优选 · 正品保障',
    heroEyebrow: '品牌故事',
    heroLead: '从一座峰到千万个家',
    heroBody: '峰峰商城创立于 2021 年,总部位于深圳。我们相信好的商品不应被地域限制,所以走了 28 个国家的仓储与认证体系,把全球优质品牌带到中国家庭的门口。',
    missionTitle: '我们的使命',
    missionBody: '让每一个中国家庭都能以透明的价格、靠谱的售后,买到全球正品好物。',
    statsTitle: '数字说朋',
    statCountries: '28',
    statCountriesLabel: '覆盖国家',
    statShops: '2,000+',
    statShopsLabel: '合作品牌',
    statUsers: '100,000+',
    statUsersLabel: '满意用户',
    statOrders: '500,000+',
    statOrdersLabel: '累计订单',
    promiseTitle: '四大保障',
    promiseShipTitle: '多仓直发',
    promiseShipDesc: '全球多仓协同，48 小时内出库',
    promiseReturnTitle: '退换无忧',
    promiseReturnDesc: '7 天无理由退换，全程跟进',
    promiseServiceTitle: '精致服务',
    promiseServiceDesc: '一对一客服，售前售后响应',
    promiseGenuineTitle: '正品保障',
    promiseGenuineDesc: '官方直采，假一赔十',
    teamTitle: '团队',
    teamLead: '一群人 · 一件事',
    teamBody: '50+ 人团队，分布在深圳、东京、新加坡。运营、设计、仓储、客服、研发，各司其职，只为做好一件事——把你选中的好东西完好送到你手里。',
    ctaTitle: '还有问题？',
    ctaBody: '客服 13:00–23:30 (UTC+8) 在线，点击右下角 Telegram 头像联系。',
    ctaButton: '联系客服',
  },
  orderDetail: {
    title: '订单详情',
    notFound: '订单不存在',
    notFoundDesc: '该订单可能已被删除或链接错误。',
    sectionItems: '商品列表',
    sectionShipping: '收货信息',
    sectionPayment: '支付信息',
    sectionStatus: '订单状态',
    statusPending: '待支付',
    statusPaid: '已支付',
    statusShipped: '已发货',
    statusDelivered: '已收货',
    statusRefunded: '已退款',
    statusCancelled: '已取消',
    subtotal: '商品小计',
    shipping: '运费',
    total: '应付总额',
    itemCount: (n: number) => `${n} 件商品`,
    copyOrderId: '复制订单号',
    copied: '已复制',
    payNow: '去支付',
    contactCs: '联系客服',
  },
  funds: {
    title: '我的资金',
    subtitle: '查看余额、冻结金额与资金流水',
    available: '可用余额',
    frozen: '冻结金额',
    earnedTotal: '累计佣金',
    withdrawnTotal: '累计提现',
    recentFlows: '最近资金流水',
    flowEmpty: '暂无资金流水',
    flowTypeIn: '入账',
    flowTypeOut: '出账',
    flowTypeFrozen: '冻结',
    flowTypeUnfreeze: '解冻',
    topupNow: '充值',
    withdrawNow: '去提现',
    /** B5: filter + export */
    monthLabel: '月份',
    monthAll: '全部月份',
    typeLabel: '类型',
    typeAll: '全部类型',
    export: '导出 CSV',
    exported: (n: number) => `已导出 ${n} 条流水`,
    noMatch: '没有匹配的流水',
  },
  team: {
    title: '我的团队',
    subtitle: '查看下级成员与推广佣金',
    memberCount: (n: number) => `${n} 人`,
    level1: '一级成员',
    level2: '二级成员',
    level3: '三级成员',
    totalCommission: '团队佣金总计',
    thisMonthCommission: '本月团队佣金',
    inviteTitle: '我的邀请码',
    inviteDesc: '复制邀请码分享给好友，对方注册后会自动成为你的下级。',
    inviteCopy: '复制',
    inviteCopied: '已复制',
    inviteCopiedToast: (code: string) => `已复制 ${code}`,
    empty: '暂无下级成员',
    emptyDesc: '分享邀请码，招募你的第一个推广者。',
    sectionMembers: '成员列表',
    memberJoinDate: '加入时间',
    memberOrderCount: '贡献订单',
    memberCommission: '贡献佣金',
    /** F1: 成员详情 modal */
    memberDetailTitle: '成员详情',
    memberClose: '关闭',
    memberAvgOrder: '平均订单金额',
    memberRecent: '最近佣金记录',
    memberRecentEmpty: '暂无佣金记录',
    memberCopyInviteLink: '复制专属邀请链接',
    memberLinkCopied: '邀请链接已复制',
  },
  commissions: {
    title: '佣金明细',
    empty: '暂无佣金记录',
    emptyDesc: '推广订单结算后会在此处显示佣金',
    totalEarned: '累计佣金',
    thisMonth: '本月佣金',
    pending: '待结算',
    available: '可提现',
    source: '来源',
    order: '订单',
    amount: '佣金金额',
    rate: '比例',
    date: '时间',
    statusSettled: '已结算',
    statusPending: '待结算',
    /** B3: filter + export */
    tabAll: '全部',
    tabSettled: '已结算',
    tabPendingTab: '待结算',
    sourceDirect: '直推',
    sourceLevel1: '1 级',
    sourceLevel2: '2 级',
    monthLabel: '月份',
    monthAll: '全部月份',
    export: '导出 CSV',
    exported: (n: number) => `已导出 ${n} 条记录`,
    noMatch: '没有匹配的记录',
    noMatchDesc: '调整状态或月份试试',
    /** B7: 佣金详情 modal */
    detailTitle: '佣金详情',
    detailClose: '关闭',
    orderId: '订单号',
    product: '商品',
    orderAmount: '订单金额',
    commissionRate: '佣金比例',
    commissionAmount: '佣金金额',
    settledAt: '结算时间',
    sourceInfo: '来源信息',
    referredBy: '推广人',
    tier: '层级',
    viewOrder: '查看订单',
    /** B8: 单笔导出 */
    exportRow: '导出这笔',
    rowExported: '单笔已导出',
  },
  withdraw: {
    title: '提现中心',
    available: '可提现余额',
    pending: '提现中',
    withdrawn: '已提现',
    apply: '申请提现',
    amount: '提现金额',
    address: '提现地址',
    selectAddress: '选择提现地址',
    noAddress: '未绑定提现地址,先在【提现地址】添加',
    history: '提现记录',
    empty: '暂无提现记录',
    /** C3: filter + export */
    tabAll: '全部',
    searchPlaceholder: '搜索 id / 地址',
    searchAria: '搜索提现记录',
    noMatch: '没有匹配的记录',
    noMatchDesc: '调整状态或搜索词试试',
    export: '导出 CSV',
    exported: (n: number) => `已导出 ${n} 条记录`,
    amountCol: '金额',
    addressCol: '提现地址',
    date: '时间',
    statusPending: '处理中',
    statusApproved: '已批准',
    statusRejected: '已拒绝',
    statusCompleted: '已完成',
    submitted: '提现申请已提交',
    minAmount: '最低提现金额 $10',
    /** C1: 资金密码 modal */
    fundPwdPrompt: '请输入资金密码',
    fundPwdHint: '6 位数字,用于提现校验',
    fundPwdWrong: '资金密码错误,请重试',
    fundPwdForgot: '忘记密码?',
    cancel: '取消',
    confirm: '确认提现',
    /** C2: 手续费预览 */
    fee: '手续费',
    feeRate: '(费率 2%)',
    actualReceive: '实际到账',
    feeHint: '最低 $10,实际到账 = 提现金额 - 手续费',
    insufficientBalance: '可提现余额不足',
    /** C4: 提现详情 modal */
    detailTitle: '提现详情',
    detailClose: '关闭',
    net: '实际到账',
    networkFee: '网络手续费',
    appliedAt: '申请时间',
    approvedAt: '批准时间',
    completedAt: '完成时间',
    rejectedAt: '拒绝时间',
    rejectReason: '拒绝原因',
    timeline: '时间线',
    timelineApplied: '已提交',
    timelineApproved: '已批准',
    timelineCompleted: '已完成',
    timelineRejected: '已拒绝',
    copyAddress: '复制地址',
    addressCopied: '地址已复制',
  },
  withdrawAddress: {
    title: '绑定提现地址',
    empty: '未绑定提现地址',
    emptyDesc: '提现地址用于接收佣金付款,加密货币或银行账户均可',
    addNew: '新增提现地址',
    type: '类型',
    typeCrypto: '加密货币',
    typeBank: '银行账户',
    label: '名称/标签',
    address: '地址 / 账号',
    network: '网络',
    save: '保存',
    cancel: '取消',
    removeConfirm: '删除该提现地址?',
    remove: '删除',
    setDefault: '设为默认',
    default: '默认',
    copy: '复制',
    copied: '已复制',
    copyErr: '复制失败',
    addrRequired: '请输入地址或账号',
    labelRequired: '请输入名称/标签',
    networkRequired: '加密货币地址必须选择网络',
    bankName: '开户银行',
    bankNamePh: '如:招商银行 / Bank of America',
    bankHolder: '开户姓名',
    bankHolderPh: '账户持有人姓名',
    bankSwift: 'SWIFT / 路由号',
    bankSwiftPh: 'SWIFT 代码或 ABA 路由号',
    bankAddr: '开户行地址',
    bankAddrPh: '可选',
    networks: {
      TRC20: 'TRC20 (Tron)',
      ERC20: 'ERC20 (Ethereum)',
      BEP20: 'BEP20 (BSC)',
      SOL: 'SOL (Solana)',
      POLYGON: 'Polygon',
      ARBITRUM: 'Arbitrum',
    },
  },
  security: {
    changePassword: '修改密码',
    changeFundPassword: '资金密码',
    currentPassword: '当前密码',
    newPassword: '新密码',
    confirmPassword: '确认新密码',
    save: '保存',
    cancel: '取消',
    pwdMismatch: '两次密码不一致',
    pwdTooShort: '密码至少 6 位',
    savedOk: '保存成功',
    fundPwdHint: '资金密码用于提现校验,6 位数字',
    pwdIntro: '至少 6 位;修改后立即生效。',
    fundPwdIntro: '资金密码仅限 6 位数字,用于提现校验。',
  },
  cookie: {
    title: '我们使用 Cookie',
    desc: '为了提供更好的浏览体验,我们使用 Cookie 记住你的偏好(如购物车、收藏、语言)。继续浏览即表示你同意这一点。',
    accept: '知道了',
    settings: '了解更多',
    aria: 'Cookie 同意',
    closeAria: '关闭',
    emoji: '🍪',
  },
  notFound: {
    eyebrow: '404',
    title: '迷路了?',
    desc: '你访问的页面不存在,可能已下架或链接拼错了。回到首页或看看热卖榜也不错。',
    home: '回到首页',
    hot: '看看热卖榜',
    code: '错误代码',
    quote: '迷路了?这里没有商品,但隔壁街区有个 12 小时限时折扣,值得一看。',
    quoteBy: '— Peak Mall 站长',
  },
  payRecords: {
    title: '支付记录',
    sub: '演示页面,所有卡号仅来自公开测试 BIN 池(非真实银行卡)。',
    nav: '支付记录',
    summaryAll: '总记录',
    summarySuccess: '已成功',
    summaryFailed: '失败',
    summaryRefund: '已退款',
    summaryAmount: '成功总额',
    byBrand: '按卡品牌',
    byStatus: '按状态',
    byDay: '近 10 天',
    tableHead: {
      time: '支付时间',
      orderId: '订单号',
      method: '方式',
      brand: '品牌',
      bin: 'BIN',
      last4: '末四位',
      amount: '金额',
      status: '状态',
      authCode: '授权码',
    },
    methodCard: '银行卡',
    methodVisa: 'Visa',
    methodMastercard: 'Mastercard',
    errorCode: {
      INSUFFICIENT_FUNDS: '余额不足',
      CARD_DECLINED: '银行拒收',
      EXPIRED: '卡片过期',
      CVV_MISMATCH: 'CVV 不匹配',
      NETWORK: '网络异常',
    },
    testBinTag: '测试 BIN',
    legend: {
      test: '测试卡 BIN',
      live: '真实 BIN(演示)',
    },
    export: '导出 CSV',
    exportNote: '仅含公开字段:BIN / 品牌 / 末四位 / 金额 / 状态 / 时间,不导出真实卡号 / CVV / 地址 / 邮箱。',
    exportDone: '已导出',
    exportedRows: (n: number) => `已导出 ${n} 条`,
    searchPlaceholder: '搜索订单号 / BIN / 末四位...',
    filterBrand: '品牌',
    filterStatus: '状态',
    filterAll: '全部',
    filterReset: '重置筛选',
    emptyResult: '没有匹配的记录',
    emptyResultDesc: '试试清空筛选或调整搜索关键词',
    showing: '显示',
    of: '/',
    matched: '条',
    detail: {
      title: '支付详情',
      close: '关闭',
      copy: '复制授权码',
      copied: '已复制',
      fields: {
        orderId: '订单号',
        method: '支付方式',
        methodCard: '银行卡',
        methodVisa: 'Visa',
        methodMastercard: 'Mastercard',
        brand: '卡品牌',
        bin: 'BIN 前 6 位',
        last4: '末四位',
        amount: '金额',
        currency: '货币',
        status: '状态',
        authCode: '授权码',
        errorCode: '错误码',
        paidAt: '支付时间',
        relativeNow: '距现在',
      },
      notCopied: '复制失败,请手动选择',
      copiedToast: '授权码已复制到剪贴板',
    },
  },
  legal: {
    termsTitle: '使用条款',
    privacyTitle: '隐私政策',
    lastUpdated: '最后更新',
    termsSections: [
      { heading: '接受条款', body: '访问或使用 Peak Mall 即表示你同意本使用条款。如果你不同意,请停止使用本服务。' },
      { heading: '服务范围', body: 'Peak Mall 是一个演示性静态电商原型,所有商品、价格、订单均为虚构数据,不代表真实商品或交易。' },
      { heading: '账户责任', body: '演示项目不要求注册,所有状态(购物车、收藏、地址、订单)仅存储于你的浏览器 localStorage,不会上传服务器。' },
      { heading: '禁止行为', body: '不得利用本项目进行任何违法活动,不得尝试逆向工程或注入恶意内容。' },
      { heading: '免责声明', body: '本项目按“现状”提供,不对任何直接或间接损失承担责任。' },
      { heading: '条款变更', body: '我们可能随时更新本条款。继续使用即视为接受变更后的版本。' },
    ],
    privacySections: [
      { heading: '我们收集什么', body: '本演示项目为纯前端静态站点,服务器不记录任何个人数据。所有交互数据(购物车、收藏、地址、订单)仅存储于你的浏览器 localStorage。' },
      { heading: 'Cookie 使用', body: '我们仅使用 Cookie / localStorage 来保存你的偏好(语言、货币、UI 设置),不会用于追踪或广告。' },
      { heading: '第三方服务', body: '本项目使用 Netlify 托管静态文件。Netlify 可能收集 IP 地址等基本访问日志,不在我们的控制范围内。' },
      { heading: '数据导出', body: '你可以通过清除浏览器数据随时删除所有本地存储。' },
      { heading: '联系', body: '如有疑问:support@peakmall.com。' },
    ],
  },
  admin: {
    roleAdmin: '总后台 · 管理员',
    roleAgent: '代理后台',
    roleFx: '分销中心',
    // Phase 3.2 — admin 2FA enrollment / re-verify
    mfaTitle: '两步验证',
    mfaSubtitle: '使用 Google Authenticator / 1Password / Authy 扫描下方二维码,并输入 6 位验证码。',
    mfaStartEnroll: '开始绑定两步验证',
    mfaScanHint: '使用验证器 app 扫描二维码:',
    mfaManualEntry: '手动输入密钥',
    mfaCodeLabel: '6 位验证码',
    mfaVerify: '验证并进入后台',
    mfaCodeInvalid: '请输入 6 位数字验证码',
    mfaVerifyFailed: '验证失败,请检查验证码是否最新',
    enrollErrorNetwork: '绑定失败,请稍后重试',
    roleSwitchHint: '当前为总后台视角。',
    loginTitle: '管理后台登录',
    loginIntro: '输入管理员账号与密码登录。账号需在 Supabase Auth 中将 role 设为 admin。',
    loginUsername: '账号',
    loginPassword: '密码',
    loginSubmit: '登录',
    loginHint: '需要管理员权限才能登录',
    loginErrorEmpty: '请输入账号与密码',
    loginErrorBad: '账号或密码错误',
    loginErrorNotAdmin: '该账号不是管理员',
    loginErrorNotConfirmed: '请先在邮箱中确认注册链接',
    loginErrorNetwork: '网络错误,请稍后重试',
    loginErrorNotConfigured: '服务器未配置鉴权,请联系运维',
    loginReasonNotAdmin: '当前账号已被取消管理员权限',
    loginChecking: '正在校验…',
    logout: '退出登录',
    gateChecking: '正在校验登录态…',
    // Phase 3.7 — admin RBAC (super_admin / ops / cs / finance)
    checkingPerms: '校验权限中…',
    noPermission: '没有访问权限',
    forbiddenReason: '当前账号无该页面权限,请联系超级管理员',
    roleSuperAdmin: '超级管理员',
    roleOps: '运营',
    roleCs: '客服',
    roleFinance: '财务',
    roleBadgeTitle: '当前角色',
    // Phase 3.7.2 — audit log page
    auditTitle: '操作日志',
    auditSubtitle: '最近 100 条 admin 操作记录。仅 super_admin 可见。',
    auditFilterResource: '按资源过滤 (orders/products/...)',
    auditFilterActor: '按操作者邮箱过滤',
    auditEmpty: '还没有操作记录。',
    auditColTime: '时间',
    auditColActor: '操作者',
    auditColAction: '动作',
    auditColResource: '资源',
    auditColDiff: '变更',
    // Phase 1.1.8 — admin data source indicator
    fromRemote: '已同步 Supabase',
    fromLocal: '本地缓存',
    syncing: '同步中…',
    groupOverview: '总览',
    groupMall: '商城管理',
    groupDistribute: '分销管理',
    groupFunds: '资金管理',
    groupTools: '工具',
    backToShop: '返回前台',
    // Phase 1.3 — admin i18n 收口
    brandName: '顶峰商城',
    leaveConfirm: '确认离开管理后台,返回前台商城?',
    saved: '已保存',
    dashboard: {
      title: '数据看板',
      kpiMembers: '分销商/代理总数',
      kpiMembersSub: (active: string, frozen: string) => `正常 ${active} / 冻结 ${frozen}`,
      kpiTotalOrder: '累计订单金额',
      kpiTotalComm: '累计佣金支出',
      kpiToday: '今日',
      kpiPendingWd: '待处理提现',
      pendingCount: (n: string) => `${n} 笔`,
      // 新增 KPI
      kpiOrderCount: '订单数',
      kpiPendingOrders: '待支付订单',
      kpiShippable: '可发货订单',
      kpiOpenTickets: '待处理工单',
      kpiGmv: '总 GMV',
      kpi7dTrend: '近 7 天趋势',
      // 跳转提示
      clickToOpen: '点击查看详情 →',
      // 最近活动
      recentOrders: '最近订单',
      recentWd: '最近提现',
      recentTickets: '最近工单',
      emptyRecent: '暂无',
      viewAll: '查看全部',
      // 系统说明
      systemNote: '系统说明',
      systemNoteBody: '这是正式版（Node + MySQL 后端），所有数据持久化存储，规则与余额由服务端计算，无法在本地篡改。\n佣金引擎：链路中遇到代理商按自有费率结算；代理直推下级的一级佣金按代理设置的比例结算（受上限约束）；其余按全局规则。',
    },
    products: {
      title: '商品管理',
      count: (n: number) => `（${n} 件）`,
      add: '新增商品',
      save: '保存',
      on: '上架',
      off: '下架',
      changeImg: '换图',
      colName: '名称',
      colCat: '分类',
      colPrice: '价格',
      colStock: '库存',
      colDesc: '描述',
      colImg: '图',
      colStatus: '状态',
      colAction: '操作',
      empty: '暂无商品',
      // 详情 modal
      detail: '商品详情',
      detailEdit: '编辑信息',
      detailCreatedAt: '上架时间',
      detailTotalValue: '库存总值',
      detailCategory: '分类',
      // 批量操作
      selectAll: '全选',
      bulkSelected: (n: number) => `已选 ${n} 件`,
      bulkOn: '批量上架',
      bulkOff: '批量下架',
      bulkClear: '取消选择',
      // 删除
      delete: '删除',
      deleteTitle: '删除商品',
      deleteBody: (n: number) => `确认删除这 ${n} 件商品？该操作不可撤销。`,
      deleteHint: '提示：下架可保留记录，删除会从商品列表彻底移除。',
      confirmDelete: '确认删除',
      // 校验
      nameRequired: '商品名称不能为空',
      priceInvalid: '价格必须 ≥ 0',
      stockInvalid: '库存必须 ≥ 0',
      skuRequired: 'SKU 不能为空',
      skuDuplicate: 'SKU 与现有商品重复',
      skuInvalid: 'SKU 仅允许字母/数字/短横线/下划线',
      stockAlertInvalid: '库存阈值必须 ≥ 0',
      comparePriceInvalid: '划线价必须 ≥ 售价',
      seoSlugInvalid: 'SEO slug 仅允许小写字母/数字/短横线',
      // 新字段
      colSku: 'SKU',
      colComparePrice: '划线价',
      colCost: '成本',
      colStockAlert: '阈值',
      colImages: '图集',
      colSeoSlug: 'SEO slug',
      colUpdatedAt: '更新时间',
      detailSku: '商品编号 (SKU)',
      detailComparePrice: '划线价 (可选)',
      detailCost: '成本 (可选)',
      detailStockAlert: '库存阈值 (≤ 此值提示补货)',
      detailImages: '图集 (回车添加,首张为主图)',
      detailImagesPh: '输入 emoji 或图片 URL,回车添加',
      detailSeoSlug: 'SEO slug',
      detailSeoSlugHint: '可选 · 小写字母/数字/短横线',
      detailDescPreview: '预览',
      detailDescEdit: '编辑',
      // 撤销
      savedToast: '已保存 · 商品 #{id}',
      undoCta: '撤销',
      undoneToast: '已撤销修改',
    },
    orders: {
      title: '订单管理',
      tabs: { all: '全部', pending: '待支付', paid: '已支付', shipped: '已发货', completed: '已完成', cancelled: '已取消' },
      colOrder: '订单号',
      colUser: '下单用户',
      colAmt: '金额',
      colStatus: '状态',
      colPay: '支付方式',
      colCard: '卡号',
      colContact: '收货人',
      colAddr: '地址',
      colTime: '时间',
      colAction: '操作',
      ship: '发货',
      shipTitle: '标记为已发货',
      shipBody: '选择物流公司并输入运单号。买家将自动收到包含物流链接的邮件。',
      complete: '完成',
      dash: '—',
      empty: '暂无订单',
      // 详情 modal
      detail: '订单详情',
      detailTitle: '订单详细信息',
      paymentSection: '支付信息',
      shippingSection: '收货信息',
      timelineSection: '进度',
      cardBrand: '卡组织',
      cardLast4: '卡号末四位',
      cardExpiry: '有效期',
      payMethod: '支付方式',
      markPaid: '标记已支付',
      retryPay: '重试支付',
      // 操作
      refund: '退款',
      cancel: '取消订单',
      // 批量
      selectAll: '全选',
      bulkSelected: (n: number) => `已选 ${n} 笔`,
      bulkShip: '批量发货',
      bulkComplete: '批量完成',
      bulkCancel: '批量取消',
      bulkClear: '取消选择',
      delete: '删除',
      // 取消/退款 modal
      cancelTitle: '取消订单',
      cancelBody: (n: number) => `确认取消这 ${n} 笔订单？取消后不可恢复。`,
      cancelReasonLabel: '取消原因',
      cancelReasonPh: '请说明取消原因（可选）',
      confirmCancel: '确认取消',
      refundTitle: '退款',
      refundBody: (amtText: string, name: string) => `确认将订单 ${name} 的 ${amtText} 全额退款？该操作不可撤销。`,
      confirmRefund: '确认退款',
      deleteTitle: '删除订单',
      deleteBody: (n: number) => `确认删除这 ${n} 笔订单？删除后不可恢复。`,
      deleteHint: '提示：取消订单会保留记录，删除会从订单列表彻底移除。',
      confirmDelete: '确认删除',
      // timeline 事件
      evtCreated: '订单创建',
      evtPaid: '支付完成',
      evtShipped: '已发货',
      evtCompleted: '订单完成',
      evtCancelled: '订单取消',
      evtRefunded: '已退款',
    },
    users: {
      title: '分销商 / 代理商',
      add: '新增',
      colRole: '角色',
      colRoleAgent: '代理商',
      colRoleFx: '分销商',
      colReferrer: '上级',
      colTeam: '团队',
      colBal: '余额',
      colStatus: '状态',
      colReg: '注册',
      colTrc20: 'TRC-20 地址',
      colAction: '操作',
      statusActive: '正常',
      statusFrozen: '冻结',
      freeze: '冻结',
      unfreeze: '解冻',
      resetPwd: '改密',
      empty: '暂无用户',
      // 详情 modal
      detail: '用户详情',
      detailTitle: '用户详细信息',
      basicSection: '账号信息',
      financeSection: '财务',
      recentOrdersSection: '该用户订单',
      recentOrdersEmpty: '该用户暂无订单',
      viewAllOrders: '查看该用户全部订单',
      roleAgent: '代理商',
      roleFx: '分销商',
      changeRole: '切换角色',
      // 批量
      selectAll: '全选',
      bulkSelected: (n: number) => `已选 ${n} 位`,
      bulkFreeze: '批量冻结',
      bulkUnfreeze: '批量解冻',
      bulkClear: '取消选择',
      delete: '删除',
      // 删除
      deleteTitle: '删除用户',
      deleteBody: (n: number) => `确认删除这 ${n} 位用户？删除后不可恢复。`,
      deleteHint: '提示：冻结会保留用户记录，删除会从用户列表彻底移除。',
      confirmDelete: '确认删除',
      // toasts
      bulkFrozenToast: (n: number) => `已冻结 ${n} 位用户`,
      bulkUnfrozenToast: (n: number) => `已解冻 ${n} 位用户`,
      bulkDeletedToast: (n: number) => `已删除 ${n} 位用户`,
      frozenToast: '已冻结',
      unfrozenToast: '已解冻',
      addedToast: '已添加新用户',
      roleChangedToast: '已切换角色',
      pwdResetToast: '密码已重置（演示）',
    },
    agents: {
      title: '代理管理 — 费率调节',
      hint: 'own_rate：代理自有佣金率（覆盖全局同级费率）；sub_rate：代理可设置直推下级的一级比例；sub_rate_limit：直推比例上限（约束代理后台调节）。',
      colOwn: '自有费率',
      colSub: '直推比例',
      colLimit: '比例上限',
      colTrc20: 'TRC-20 地址',
      colAction: '操作',
      save: '保存',
      empty: '暂无代理',
      saved: '已保存',
      copyAddress: '复制地址',
      copied: '已复制',
      copyErr: '复制失败',
      rangeErr: '费率范围 0–100,直推比例不能超过上限',
      savedToast: '已保存 · 代理 #{id}',
      undoCta: '撤销',
      undoneToast: '已撤销修改',
    },
    invite: {
      title: '邀请码管理',
      add: '生成邀请码',
      colCode: '邀请码',
      colUsed: '已用 / 上限',
      colStatus: '状态',
      colTime: '创建时间',
      colAction: '操作',
      disable: '禁用',
      enable: '启用',
      empty: '暂无邀请码',
    },
    tickets: {
      title: '售后管理',
      colOrder: '订单号',
      colUser: '用户',
      colReason: '原因',
      colStatus: '状态',
      colTime: '时间',
      colAction: '操作',
      reply: '回复',
      close: '关闭',
      empty: '暂无售后',
      // 详情 modal
      detail: '售后详情',
      detailTitle: '售后详细信息',
      orderSection: '订单',
      contentSection: '诉求',
      replySection: '客服回复',
      replyPh: '输入回复内容，发送后状态自动变为「已回复」',
      noReply: '尚未回复',
      replySavedAt: (t: string) => `回复于 ${t}`,
      // 状态
      statusOpen: '待处理',
      statusReplied: '已回复',
      statusClosed: '已关闭',
      // 批量
      selectAll: '全选',
      bulkSelected: (n: number) => `已选 ${n} 条`,
      bulkReply: '批量标记已回复',
      bulkClose: '批量关闭',
      bulkClear: '取消选择',
    },
    rules: {
      title: '佣金规则设置',
      ownRate: '自购返佣比例 (%)',
      minWd: '最低提现金额',
      fee: '提现手续费 (%)',
      mode: '结算模式',
      modeVal: '自购返佣（只结算下单人本人）',
      hint: '二、三级分佣已停用，佣金只结算给下单人本人',
      commissionOn: '开启佣金结算',
      autoApprove: '提现免审核（自动通过）',
      saveAll: '保存全部设置',
      // validation
      rangeErr: '佣金/费率必须在 0–100 之间',
      minWdErr: '最低提现金额必须 ≥ 0',
      // feedback
      savedToast: '已保存佣金规则',
      noChanges: '没有需要保存的修改',
      unsaved: '有未保存的修改',
    },
    comm: {
      title: '佣金流水',
      colUser: '用户',
      colAmt: '佣金金额',
      colSource: '来源订单',
      colRate: '费率',
      colStatus: '状态',
      colTime: '时间',
      settled: '已结算',
      pending: '待结算',
      empty: '暂无流水',
    },
    wd: {
      title: '提现审核',
      colId: '单号',
      colUser: '用户',
      colAmt: '金额',
      colFee: '手续费',
      colMethod: '方式',
      colReject: '驳回原因',
      colStatus: '状态',
      colTime: '申请时间',
      colProcessed: '处理时间',
      colAddr: '绑定TRC-20地址',
      colAction: '操作',
      approve: '通过',
      reject: '驳回',
      markPaid: '标记已到账',
      view: '查看',
      unbound: '未绑定',
      addrMismatch: '⚠ 与提现单地址不一致',
      empty: '暂无记录',
      // modal 文案
      rejectTitle: '驳回提现申请',
      rejectReasonLabel: '驳回原因',
      rejectReasonPh: '请说明驳回原因(将记录在订单中)',
      rejectReasonRequired: '驳回原因不能为空',
      cancel: '取消',
      confirmReject: '确认驳回',
      approveTitle: '确认通过提现',
      approveBodyApprove: '将通过本次提现申请，用户可在状态变为「已通过」后等待出账。',
      approveBodyPay: '标记该申请已实际到账，并从用户余额中扣除本单金额。',
      approveNetLabel: '实际到账金额',
      approveFeeLabel: '手续费',
      confirmApprove: '确认通过',
      confirmPay: '确认到账',
      paidTitle: '确认已到账',
      paidBody: '标记该申请已实际到账。此操作会从用户余额中扣除提现金额。',
      // toasts
      approvedToast: (id: number) => `已通过提现 #${id}`,
      rejectedToast: (id: number) => `已驳回提现 #${id}`,
      paidToast: (id: number) => `已到账 #${id}`,
    },
    wdCenter: {
      title: '提现中心',
      tabs: { all: '全部', pending: '待审核', approved: '已通过', rejected: '已驳回', paid: '已到账' },
      colId: '单号',
      colAmt: '金额',
      colFee: '手续费',
      colMethod: '方式',
      colAccount: '账户',
      colStatus: '状态',
      colReject: '驳回原因',
      colTime: '时间',
      colAction: '操作',
      apply: '申请提现',
      balance: '可提现余额',
      min: '最低提现',
      empty: '暂无提现',
      applySuccess: '提现申请已提交，等待后台审核。',
      applyFailMin: '金额不能低于最低提现额。',
      applyFailInsufficient: '可提现余额不足。',
      applyFailAddr: 'USDT-TRC20 提现需先绑定收款地址。',
      submitted: '已提交',
      accountLabel: '收款账户 / 地址',
      accountPh: '输入 USDT-TRC20 地址或银行卡号',
      insufficientBalance: '余额不足',
      needBind: '需绑定地址',
      currentUserLabel: '当前账号',
      switchUser: '切换演示账号',
    },
    home: {
      title: '首页设置',
      heroTitle: '轮播主标题',
      heroSub: '轮播副标题 / 品牌口号',
      notice: '全场公告（留空不显示）',
      hint: '提示：轮播主标题会覆盖首页首屏大标题；副标题同时用于首页推荐区与页脚简介；公告显示在首屏下方的滚动条。',
      save: '保存',
      preview: '效果预览',
      phTitle: '全球精选 · 品质好物',
      phSub: '官方直采 · 正品保障 · 多仓直发',
      phNotice: '新用户注册即享专属礼遇 · 全场正品保障',
    },
    support: {
      title: '客服设置',
      name: '客服名称',
      url: '客服链接（Telegram）',
      hours: '在线时间',
      save: '保存',
      preview: '效果预览',
      phUrl: 'https://t.me/YourChannel',
      phHours: '13:00 - 23:30',
      hintUrl: '填写完整链接，例如 https://t.me/MementoCare',
      hintHours: '留空则客服卡片不显示在线时间',
    },
    audit: {
      title: '操作日志',
    },
    demo: {
      title: '模拟下单',
      hint: '在演示环境中触发一笔虚拟订单，方便查看订单管理与提现审核的数据流。',
      trigger: '生成一笔订单',
      lastOrder: '最近一次生成',
      none: '尚未生成',
    },
  },
  /** v41: 代理 / 分销中心首页文案 */
  agentDash: {
    title: '分销商中心',
    balance: '我的余额',
    quickActions: '快捷操作',
    withdraw: '提现中心',
    bindAddress: '绑定提现地址',
    commDetail: '佣金明细',
    teamMgmt: '团队管理',
  },
  /** v41: 分销中心 alias (fx page 共用同一组文案) */
  fxDash: {
    title: '分销商中心',
    balance: '我的余额',
    quickActions: '快捷操作',
    withdraw: '提现中心',
    bindAddress: '绑定提现地址',
    commDetail: '佣金明细',
    teamMgmt: '团队管理',
  },
  // Phase 3.3.2 — status page
  status: {
    title: '服务状态',
    subtitle: '实时健康检查 · 每 30 秒刷新',
    probeError: '无法连接到状态服务',
    loading: '检查中…',
    allOk: '所有服务正常',
    someIssues: '部分服务异常,功能可能受限',
    ok: 'OK',
    down: '异常',
    colService: '服务',
    colStatus: '状态',
    colLatency: '延迟',
    colDetail: '详情',
    lastCheck: '最后检查',
  },
} as const;
