/**
 * 集中文案表 - 替代散落的 [COPY:xxx] 占位
 *
 * 红线:本文案基于参考站结构改写,不直接复用源站字
 * 每条都要过一遍:
 *   1. 不抄原表述
 *   2. 不抄具体金额/折扣/优惠条件
 *   3. 不实现强制邀请码/分销/提现
 *
 * 改了这里,所有组件 / 页面会同步生效
 */

export const COPY = {
  brand: {
    name: '顶峰商城',
    slogan: 'PEAK MALL',
    intro: '全球优选 · 正品保障。28 国配送,7 天无理由退换。',
    shortName: '顶峰',
  },

  nav: {
    home: '首页',
    all: '全部',
    new: '新品',
    hot: '热卖',
    orders: '我的订单',
    after: '售后',
    about: '关于',
  },

  currencyLabel: {
    USD: 'USD 美元',
    CNY: 'CNY 人民币',
    EUR: 'EUR 欧元',
    GBP: 'GBP 英镑',
    JPY: 'JPY 日元',
    KRW: 'KRW 韩元',
    AUD: 'AUD 澳元',
    CAD: 'CAD 加元',
  },

  langLabel: { zh: '中文', en: 'EN' },

  header: {
    welcome: '您好,欢迎来到顶峰',
    login: '登录 / 注册',
    searchAria: '站内搜索',
    inputAria: '搜索商品',
    submit: '搜索',
    orderStatus: '订单状态',
  },

  announcement: {
    defaultTag: '公告',
    defaultText: '全场满 $50 包邮 · 7 天无理由退换',
  },

  card: {
    wishlistOn: '♥',
    wishlistOff: '♡',
    addedToCart: '✓ 已加入',
  },

  modal: {
    close: '关闭',
    closeSymbol: '✕',
    coverEmoji: '📦',
  },

  auth: {
    loginTitle: '登录顶峰',
    loginSub: '使用任意邮箱与密码(演示模式)',
    registerTitle: '注册新账户',
    registerSub: '加入 10 万+ 满意用户',
    hero: '欢迎来到顶峰',
    login: '登录账户',
    register: '注册新账户',
    email: '邮箱',
    emailPh: 'you@example.com',
    password: '密码',
    passwordPh: '至少 8 位',
    password2: '确认密码',
    password2Ph: '再输入一次',
    nickname: '昵称',
    nicknamePh: '选一个好记的',
    invite: '邀请码',
    invitePh: '可选',
    remember: '记住我',
    pwMismatch: '两次密码不一致',
    errGeneric: '出错了,请稍后再试',
    announce: '登录后享受会员价 · 历史订单随时查',
    loginErrorShort: '密码至少 6 位',
    registerErrorShort: '密码至少 6 位',
    loginErrorGeneric: '登录失败',
    registerErrorGeneric: '注册失败',
    loggedInAs: (email: string, at: string) => `已登录为 ${email} · 登录于 ${at}`,
  },
  cta: {
    addToCart: '加入购物车',
    buyNow: '立即购买',
    viewDetail: '查看详情',
    backToHome: '返回首页',
    goLogin: '去登录',
    goRegister: '去注册',
    subscribe: '立即订阅',
    emailPh: '输入邮箱地址',
    emailLabel: '邮箱地址',
    label: '限时福利',
    title: '订阅获取专属折扣',
    sub: '新用户首单立享额外优惠 · 每周精选商品推荐 · 随时退订',
    success: '订阅成功!请在邮箱中查收欢迎邮件。',
    error: '请输入有效的邮箱地址。',
    disclaimer: '我们尊重您的隐私,可随时退订。详情请见《隐私政策》。',
  },
  label: {
    inStock: '现货',
    outOfStock: '缺货',
    pcs: '件',
    price: '价格',
    category: '分类',
    stock: '库存',
    createdAt: '上架时间',
    noDescription: '暂无详细描述',
  },
  service: {
    shipping: { title: '多仓直发', desc: '全球 28 国配送' },
    return: { title: '退换无忧', desc: '7 天无理由' },
    support: { title: '精致服务', desc: '13:00-23:30 在线' },
    authentic: { title: '正品保障', desc: '假一赔十' },
  },
  footer: {
    col1: '购物',
    col2: '账户',
    col3: '帮助',
    col4: '联系',
    all: '全部商品',
    new: '新品上架',
    hot: '热卖榜单',
    about: '关于我们',
    orders: '我的订单',
    wishlist: '我的收藏',
    address: '收货地址',
    aftersales: '售后服务',
    shipping: '配送说明',
    terms: '使用条款',
    privacy: '隐私政策',
    account: '个人中心',
    hours: (h: string) => `服务时间: ${h}`,
    rights: '保留所有权利',
  },
  product: {
    spec: '规格参数',
    rating: '用户评分',
    related: '看了又看',
    qty: '数量',
    addSuccess: '已加入购物车',
    loginRequired: '请先登录',
  },
  hero: {
    h1: '精选全球好物',
    h2: '品质生活 一站即达',
    sub: '数码电子 · 智能家居 · 28 国直邮 · 7 天无理由退换',
    eyebrow: '限时活动 · 全场满 $50 包邮',
    ctaPrimary: '立即选购',
    ctaSecondary: '查看热卖',
    socialProof: '10 万 + 用户的选择',
    rating: '4.9 / 5.0',
    floatingCard1: '已发货',
    floatingCard1Sub: '预计 3 天到达',
    floatingCard2: '购买体验非常好,客服响应快,物流准时!',
    searchPlaceholder: '搜索 16 万件好物 · 笔记本 / 耳机 / 扫地机 …',
    searchHint: '热门:',
    searchTags: ['商务本', '真无线耳机', '扫地机器人', '智能手表'],
    trust: {
      countries: '覆盖国家',
      countryUnit: '+',
      support: '在线客服',
      supportUnit: '',
      return: '无理由退换',
      returnUnit: '天',
      authentic: '正品保障',
      authenticUnit: '',
    },
  },
  home: {
    browseByCat: '分类浏览',
    exploreCategories: '探索精选分类',
    cat1Desc: '从商务本到智能穿戴,覆盖数字生活每一面',
    cat2Desc: '智能家居升级,让日常更轻松更高效',
    catOfItems: (n: number) => `${n} 件好物`,
  },
  flashSale: {
    label: '限时秒杀',
    title: '12 小时限时折扣',
    scope: '全场通用 · 仅此一波',
    endsIn: '距结束',
    stock: '剩余库存',
    save: '立省',
  },
  topSelling: {
    label: '本周热销榜',
    title: 'TOP 5 用户最爱',
    viewAll: '查看完整榜单',
    sold: '已售',
  },
  rec: {
    label: '为您推荐',
    title: '精选推荐',
    sub: '基于浏览历史与热销数据智能推荐',
    sortBy: '排序',
    sortDefault: '综合排序',
    sortPriceAsc: '价格从低到高',
    sortPriceDesc: '价格从高到低',
    sortRating: '好评优先',
    empty: '该分类暂无商品,试试其他分类',
  },
  quality: {
    label: '品质专区',
    title: '两大精选系列',
    collection: '精选系列',
    cat1: '数码电子',
    cat2: '家用电器',
    b1Title: '数码旗舰专区',
    b1Sub: '从商务办公到日常娱乐,旗舰品质,全球优选',
    b1Bullets: ['商务本 · 旗舰性能', '智能穿戴 · 健康追踪', '音频 · 沉浸体验'],
    b1Cta: '进入数码',
    b2Title: '智能家居专区',
    b2Sub: '科技点亮生活,让日常家务更轻松',
    b2Bullets: ['扫地机器人 · LiDAR 导航', '智能音箱 · 语音控制', '安防监控 · 24h 守护'],
    b2Cta: '进入家居',
  },
  newArrivals: {
    label: '新品上市',
    title: '刚上架 · 抢先看',
    viewAll: '查看全部新品',
    badge: 'NEW',
    hot: '首发',
  },
  testimonial: {
    label: '真实评价',
    title: '听听他们怎么说',
    aggregate: '4.9 · 来自 10,000+ 用户',
    q1: '第一次在顶峰商城购物,体验超出预期。包装严实,发货速度很快,商品质量也对得起价格。',
    n1: '陈女士',
    r1: '北京 · 数码爱好者',
    q2: '买了商务本和真无线耳机,都是正品,价格比专柜便宜不少。客服回复也很专业。',
    n2: '李先生',
    r2: '上海 · 商务人士',
    q3: '智能家居系列质量不错,扫地机器人很智能,APP 控制也很流畅。已经回购了三次。',
    n3: '王女士',
    r3: '深圳 · 设计师',
  },
  promise: {
    label: '我们的承诺',
    title: '四大保障,买得放心',
  },
  shop: {
    notFoundTitle: '商品不存在',
    notFoundDesc: '商品可能已下架,或链接有误。',
  },
  cart: {
    title: '我的购物车',
    empty: '购物车是空的',
    emptyDesc: '去看看有什么好物吧',
    total: '合计',
    checkout: '去结算',
    clear: '清空购物车',
    continue: '继续购物',
    qty: '数量',
    subtotal: '小计',
    orderPlaced: '订单已生成',
    orderPlacedDesc: '请在“我的订单”中查看状态',
    removed: '已移除',
    freeShippingNote: '免运费',
    shippingFee: '$5.00',
    shippingLabel: '运费',
    qtyDecLabel: '减少数量',
    qtyIncLabel: '增加数量',
  },

  search: {
    title: '搜索结果',
    subCount: (n: number, q: string) => `共 ${n} 件商品匹配“${q}”`,
    subEmpty: (q: string) => `未找到匹配“${q}”的商品`,
    suggest: '试试其他关键词，或返回首页继续逛逛',
    clear: '清空',
    backHome: '返回首页',
    hot: '热门关键词',
    hotTags: ['笔记本', '耳机', '扫地机器人', '智能手表', '加湿器'],
  },
  orders: {
    title: '我的订单',
    empty: '暂无订单',
    emptyDesc: '下单后会显示在这里',
    startShopping: '去购物',
    itemCount: (n: number) => `${n} 件商品`,
    orderId: '订单号',
    placedAt: '下单时间',
    status: '状态',
    amount: '金额',
    viewDetail: '查看详情',
    statusPending: '待支付',
    statusPaid: '已支付',
    statusShipped: '已发货',
    statusDelivered: '已签收',
  },
  profile: {
    title: '个人中心',
    hello: '您好,欢迎来到顶峰',
    notLoggedIn: '请先登录后查看个人中心',
    goLogin: '去登录',
    accountInfo: '账户信息',
    nickname: '昵称',
    email: '邮箱',
    edit: '编辑',
    quickLinks: '快捷入口',
    myOrders: '我的订单',
    myWishlist: '我的收藏',
    cart: '购物车',
    settings: '账户设置',
    logout: '退出登录',
    memberSince: '加入时间',
  },
  wishlist: {
    title: '我的收藏',
    empty: '还没有收藏任何商品',
    emptyDesc: '在心形按钮上点击,把喜欢的商品加入这里',
    addToCart: '加入购物车',
    removeAll: '清空收藏',
    addedAt: '收藏于',
  },
  address: {
    title: '我的地址',
    empty: '还没有保存地址',
    emptyDesc: '添加收货地址,下单时自动填充',
    addNew: '新增地址',
    edit: '编辑',
    remove: '删除',
    setDefault: '设为默认',
    default: '默认',
    name: '收货人',
    phone: '手机号',
    region: '省市区',
    detail: '详细地址',
    save: '保存',
    cancel: '取消',
    removeConfirm: '确定删除该地址吗?',
  },
  aftersale: {
    title: '我的售后',
    empty: '没有售后记录',
    emptyDesc: '订单有售后需求时可在此发起申请',
    requestBtn: '申请售后',
    orderId: '订单号',
    reason: '原因',
    statusPending: '待处理',
    statusApproved: '已通过',
    statusRejected: '已拒绝',
    statusCompleted: '已完成',
    statusRefunded: '已退款',
    note: '说明',
    submitOk: '售后申请已提交',
    viewOrder: '查看订单',
  },
  commissions: {
    title: '佣金明细',
    empty: '暂无佣金记录',
    emptyDesc: '推广订单结算后会在此处显示佣金',
    totalEarned: '累计佣金',
    thisMonth: '本月佣金',
    pending: '待结算',
    available: '可提现',
    source: '来源',
    order: '订单',
    amount: '佣金金额',
    rate: '比例',
    date: '时间',
    statusSettled: '已结算',
    statusPending: '待结算',
  },
  withdraw: {
    title: '提现中心',
    available: '可提现余额',
    pending: '提现中',
    withdrawn: '已提现',
    apply: '申请提现',
    amount: '提现金额',
    address: '提现地址',
    selectAddress: '选择提现地址',
    noAddress: '未绑定提现地址,先在【提现地址】添加',
    history: '提现记录',
    empty: '暂无提现记录',
    statusPending: '处理中',
    statusApproved: '已批准',
    statusRejected: '已拒绝',
    statusCompleted: '已完成',
    submitted: '提现申请已提交',
    minAmount: '最低提现金额 $10',
  },
  withdrawAddress: {
    title: '绑定提现地址',
    empty: '未绑定提现地址',
    emptyDesc: '提现地址用于接收佣金付款,加密货币或银行账户均可',
    addNew: '新增提现地址',
    type: '类型',
    typeCrypto: '加密货币',
    typeBank: '银行账户',
    label: '名称/标签',
    address: '地址 / 账号',
    network: '网络',
    save: '保存',
    cancel: '取消',
    removeConfirm: '删除该提现地址?',
    remove: '删除',
    setDefault: '设为默认',
    default: '默认',
  },
  security: {
    changePassword: '修改密码',
    changeFundPassword: '资金密码',
    currentPassword: '当前密码',
    newPassword: '新密码',
    confirmPassword: '确认新密码',
    save: '保存',
    cancel: '取消',
    pwdMismatch: '两次密码不一致',
    pwdTooShort: '密码至少 6 位',
    savedOk: '保存成功',
    fundPwdHint: '资金密码用于提现校验,6 位数字',
  },
  cookie: {
    title: '我们使用 Cookie',
    desc: '为了提供更好的浏览体验,我们使用 Cookie 记住你的偏好(如购物车、收藏、语言)。继续浏览即表示你同意这一点。',
    accept: '知道了',
    settings: '了解更多',
    aria: 'Cookie 同意',
    closeAria: '关闭',
    emoji: '🍪',
  },
  notFound: {
    eyebrow: '404',
    title: '迷路了?',
    desc: '你访问的页面不存在,可能已下架或链接拼错了。回到首页或看看热卖榜也不错。',
    home: '回到首页',
    hot: '看看热卖榜',
    code: '错误代码',
    quote: '迷路了?这里没有商品,但隔壁街区有个 12 小时限时折扣,值得一看。',
    quoteBy: '— Peak Mall 站长',
  },
  payRecords: {
    title: '支付记录',
    sub: '演示页面,所有卡号仅来自公开测试 BIN 池(非真实银行卡)。',
    nav: '支付记录',
    summaryAll: '总记录',
    summarySuccess: '已成功',
    summaryFailed: '失败',
    summaryRefund: '已退款',
    summaryAmount: '成功总额',
    byBrand: '按卡品牌',
    byStatus: '按状态',
    byDay: '近 10 天',
    tableHead: {
      time: '支付时间',
      orderId: '订单号',
      method: '方式',
      brand: '品牌',
      bin: 'BIN',
      last4: '末四位',
      amount: '金额',
      status: '状态',
      authCode: '授权码',
    },
    methodCard: '银行卡',
    methodWallet: '钱包',
    methodBank: '网银',
    errorCode: {
      INSUFFICIENT_FUNDS: '余额不足',
      CARD_DECLINED: '银行拒收',
      EXPIRED: '卡片过期',
      CVV_MISMATCH: 'CVV 不匹配',
      NETWORK: '网络异常',
    },
    testBinTag: '测试 BIN',
    legend: {
      test: '测试卡 BIN',
      live: '真实 BIN(演示)',
    },
    export: '导出 CSV',
    exportNote: '仅含公开字段:BIN / 品牌 / 末四位 / 金额 / 状态 / 时间,不导出真实卡号 / CVV / 地址 / 邮箱。',
    exportDone: '已导出',
    exportedRows: (n: number) => `已导出 ${n} 条`,
    searchPlaceholder: '搜索订单号 / BIN / 末四位...',
    filterBrand: '品牌',
    filterStatus: '状态',
    filterAll: '全部',
    filterReset: '重置筛选',
    emptyResult: '没有匹配的记录',
    emptyResultDesc: '试试清空筛选或调整搜索关键词',
    showing: '显示',
    of: '/',
    matched: '条',
    detail: {
      title: '支付详情',
      close: '关闭',
      copy: '复制授权码',
      copied: '已复制',
      fields: {
        orderId: '订单号',
        method: '支付方式',
        methodCard: '银行卡',
        methodWallet: '钱包',
        methodBank: '网银',
        brand: '卡品牌',
        bin: 'BIN 前 6 位',
        last4: '末四位',
        amount: '金额',
        currency: '货币',
        status: '状态',
        authCode: '授权码',
        errorCode: '错误码',
        paidAt: '支付时间',
        relativeNow: '距现在',
      },
      notCopied: '复制失败,请手动选择',
      copiedToast: '授权码已复制到剪贴板',
    },
  },
} as const;
